/**
 * HDR bloom composite strategies.
 *
 * Each strategy is one complete answer to "how should the sharp scene and the
 * three bloom brackets become one image". Strategies are kept side by side
 * rather than replaced so visual experiments stay reproducible: a render from
 * six months ago can be regenerated by name instead of by git archaeology.
 *
 * A strategy owns both halves of the algorithm:
 *   - `brackets`, consumed by the bracket-capture loop in `preview.ts`, and
 *   - `fragmentShader`, the composite itself.
 *
 * These co-evolved historically (the linear-hdr strategy scales bloom strength
 * globally; only chroma-shoulder ramps the high bracket's threshold), so a
 * shader alone does not reproduce a past render.
 */

/** Bracket-capture parameters. Index order is always [low, mid, high]. */
export interface HdrBloomBracketConfig {
    /** Per-bracket multipliers applied to the configured bloom strength. */
    factors: readonly [number, number, number];
    /** Global multiplier applied to bloom strength before the factors. */
    strengthScale: number;
    /**
     * Per-bracket multipliers on the bloom blur radius.
     *
     * All-1 (the historical setup) makes the three brackets differ only in
     * intensity: they are near-scalar multiples of one another, so no amount of
     * bracket selection can recover information one of them lacks. Giving a
     * bracket a wider radius makes it a genuinely different spatial scale,
     * which is what lets a blown-out highlight pick up the hue of the region
     * around it instead of its own white core.
     */
    radiusScales: readonly [number, number, number];
    /** High-bracket bloom threshold at globalBloomBias 0. */
    highThresholdDark: number;
    /** High-bracket bloom threshold at globalBloomBias 1. */
    highThresholdBright: number;
    /**
     * Capture brackets with the custom acrylic PSF pipeline instead of
     * UnrealBloom: vec4(emission, coverage) fields at compounding sigmas,
     * pure (no strength/threshold baked in). The composite receives strength
     * via the bloomStrength uniform, so the shader alone reproduces a render.
     */
    customPsf?: boolean;
    /**
     * Per-mip contribution for UnrealBloom's five spatial bands.
     *
     * The first two bands are local (roughly the LED and its immediate
     * axial/diagonal neighbours at production resolution); level 3 is a
     * mid-frequency bridge; levels 4-5 are coarse, low-frequency fields.
     * Omitted means the historical all-mip response. Custom-PSF strategies
     * ignore this setting.
     */
    unrealMipWeights?: readonly [number, number, number, number, number];
}

export interface HdrBloomStrategy {
    name: HdrBloomStrategyName;
    /** Short label burned into comparison grids. */
    label: string;
    description: string;
    brackets: HdrBloomBracketConfig;
    fragmentShader: string;
    /**
     * Whether `bloom-utils.compositeHdrBloomRgba` mirrors this shader. Only the
     * default strategy has a CPU oracle; verifying any other against it would
     * compare two different algorithms.
     */
    supportsCpuOracle: boolean;
}

export const HDR_BLOOM_STRATEGY_NAMES = [
    'chroma-shoulder',
    'linear-hdr',
    'chroma-capped',
    'white-core-chroma',
    'sliding-window',
    'wide-surround-chroma',
    'surround-white-safe',
    'norm-tonescale',
    'surround-white-glow',
    'norm-tonescale-guarded',
    'norm-tonescale-sharp',
    'norm-surround-hue',
    'legacy-additive',
    'acrylic-overflow',
    'acrylic-pane-wide',
    'acrylic-pane',
    'acrylic-psf',
    'acrylic-native',
    'hdr-reference',
] as const;

export type HdrBloomStrategyName = (typeof HDR_BLOOM_STRATEGY_NAMES)[number];

/**
 * The shipped composite.
 *
 * Promoted after the issue #493 frosted-acrylic directive: the panel must
 * behave like LEDs behind a frosted acrylic diffuser — glow grows steeply
 * with drive level, a fully driven white region whites out into one pane
 * (matching the legacy additive bloom's diffusion response), while colored
 * light keeps its hue past threshold instead of clipping per-channel to
 * white, and unlit panel stays black. Measured on fluid_eyes3 (64x64,
 * mapped-led) against a minimal-bloom reference: white-out ratio 0.473
 * (legacy 0.466, norm-tonescale-guarded 0.426), white-bloom aliveness +4.25,
 * hue fidelity 0.246/0.382 vs legacy's 0.070/0.074, zero shadow veil vs
 * legacy's 0.752. Confirmed on the color_bubble_swirl hold-out clip
 * (hue fidelity 0.789/0.815) and the sparse ring_24 map. Round 6 added the
 * pane mechanism on top (drive-dependent core softening) after frame review
 * showed fully driven regions still reading as sharp dots over glow; the
 * strengthened constants merge the hot core into one pane while keeping the
 * zero veil and the hue machinery intact.
 */
export const DEFAULT_HDR_BLOOM_STRATEGY: HdrBloomStrategyName = 'acrylic-pane';

/**
 * The one strategy `bloom-utils.compositeHdrBloomRgba` mirrors.
 *
 * Deliberately NOT tied to the default: the CPU oracle exists to verify the
 * GPU path against a known twin, and it mirrors chroma-shoulder specifically.
 * Promoting a new default must not silently repoint the oracle at an algorithm
 * it does not implement.
 */
export const CPU_ORACLE_HDR_BLOOM_STRATEGY: HdrBloomStrategyName = 'chroma-shoulder';

/** Bracket setup used by every strategy that did not customize it. */
const STANDARD_BRACKETS: HdrBloomBracketConfig = {
    factors: [0.20, 0.55, 1],
    strengthScale: 1,
    radiusScales: [1, 1, 1],
    highThresholdDark: 0.08,
    highThresholdBright: 0.16,
};

/** Shared GLSL: transfer functions and the v1-compatible smoothstep. */
const PRELUDE = /* glsl */`
precision highp float;

uniform sampler2D rawFrame;
uniform sampler2D lowFrame;
uniform sampler2D midFrame;
uniform sampler2D highFrame;
uniform float globalBloomBias;
uniform float bloomStrength;
varying vec2 vUv;

float v1Smoothstep(float edge0, float edge1, float value) {
    float t = clamp((value - edge0) / max(edge1 - edge0, 1e-9), 0.0, 1.0);
    return t * t * (3.0 - 2.0 * t);
}

vec3 linearToSrgb(vec3 value) {
    value = max(value, vec3(0.0));
    bvec3 cutoff = lessThanEqual(value, vec3(0.0031308));
    vec3 lower = value * 12.92;
    vec3 higher = 1.055 * pow(value, vec3(1.0 / 2.4)) - 0.055;
    return mix(higher, lower, cutoff);
}

float srgbToLinear(float value) {
    return value <= 0.04045
        ? value / 12.92
        : pow((value + 0.055) / 1.055, 2.4);
}

float maxChannel(vec3 value) { return max(max(value.r, value.g), value.b); }
float minChannel(vec3 value) { return min(min(value.r, value.g), value.b); }
`;

/** The white-merge detector shared by the three historical strategies. */
const V1_RISK_FUNCTIONS = /* glsl */`
float pixelWhiteMergeRisk(vec3 raw, vec3 bloomed) {
    float rawMax = maxChannel(raw);
    if (rawMax < 0.04) return 0.0;
    float rawMin = minChannel(raw);
    float bloomMax = maxChannel(bloomed);
    float bloomMin = minChannel(bloomed);
    float rawSaturation = (rawMax - rawMin) / max(rawMax, 1e-9);
    float bloomSaturation = (bloomMax - bloomMin) / max(bloomMax, 1e-9);
    float colorWash = v1Smoothstep(0.72, 0.98, bloomMin)
        * max(rawSaturation - bloomSaturation, 0.0);
    float clippedDetail = v1Smoothstep(0.82, 0.995, bloomMax)
        * v1Smoothstep(0.03, 0.22, bloomMax - rawMax)
        * v1Smoothstep(0.30, 0.85, rawMax);
    return max(colorWash, clippedDetail * 0.65);
}

float shadowBloomWeight(vec3 raw, vec3 bloomed) {
    float rawMax = maxChannel(raw);
    if (rawMax >= 0.04) return 1.0;
    float bloomMax = maxChannel(bloomed);
    return v1Smoothstep(0.025, 0.14, bloomMax);
}
`;

/**
 * Current production shader (commit 584baa8), preserved verbatim so the default
 * strategy stays byte-identical to renders made before the registry existed.
 */
const CHROMA_SHOULDER_SHADER = PRELUDE + V1_RISK_FUNCTIONS + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    vec3 raw = linearToSrgb(rawLinear);
    vec3 mid = linearToSrgb(midLinear);
    vec3 high = linearToSrgb(highLinear);
    float highRisk = pixelWhiteMergeRisk(raw, high);
    float midRisk = pixelWhiteMergeRisk(raw, mid);
    float highWeight = (1.0 - v1Smoothstep(0.035, 0.20, highRisk))
        * mix(1.0, 0.15, globalBloomBias);
    float midWeight = (1.0 - v1Smoothstep(0.05, 0.24, midRisk))
        * mix(1.0, 0.35, globalBloomBias);
    vec3 upperLinear = mix(midLinear, highLinear, highWeight);
    vec3 selectedLinear = mix(lowLinear, upperLinear, midWeight);

    vec3 selectedAdded = max(selectedLinear - rawLinear, vec3(0.0));
    float neutralBloom = minChannel(selectedAdded);
    float protectedNeutral = neutralBloom * shadowBloomWeight(raw, high);

    vec3 highAdded = max(highLinear - rawLinear, vec3(0.0));
    float highNeutral = minChannel(highAdded);
    vec3 highChroma = max(highAdded - vec3(highNeutral), vec3(0.0));
    float highAddedEnergy = maxChannel(highAdded);
    float chromaEnergy = maxChannel(highChroma);
    float chromaPurity = chromaEnergy / max(highAddedEnergy, 1e-9);
    float sceneChromaScale = mix(1.0, 0.65, globalBloomBias);
    float chromaGate = v1Smoothstep(srgbToLinear(0.015), srgbToLinear(0.07), chromaEnergy)
        * v1Smoothstep(0.08, 0.40, chromaPurity)
        * sceneChromaScale;

    float chromaShoulder = srgbToLinear(0.40);
    float mappedChromaEnergy = chromaShoulder
        * (1.0 - exp(-chromaEnergy / max(chromaShoulder, 1e-9)));
    float chromaScale = chromaEnergy > 1e-9
        ? mappedChromaEnergy / chromaEnergy
        : 0.0;
    vec3 chromaticBloom = highChroma * chromaScale * chromaGate;

    float saturationProtection = v1Smoothstep(0.15, 0.65, chromaPurity);
    protectedNeutral *= mix(1.0, 0.30, saturationProtection);

    float rawMax = maxChannel(raw);
    float darkMask = 1.0 - v1Smoothstep(0.02, 0.12, rawMax);
    float baseLimitSrgb = mix(0.18, 0.11, globalBloomBias);
    float neutralLimit = mix(1.0, srgbToLinear(baseLimitSrgb), darkMask);
    float neutralHeadroom = max(minChannel(vec3(1.0) - rawLinear), 0.0);
    float neutralAdded = min(min(protectedNeutral, neutralLimit), neutralHeadroom);

    vec3 baseWithNeutral = rawLinear + vec3(neutralAdded);
    vec3 available = max(vec3(1.0) - baseWithNeutral, vec3(0.0));
    float hueSafeScale = 1.0;
    if (chromaticBloom.r > 1e-9) hueSafeScale = min(hueSafeScale, available.r / chromaticBloom.r);
    if (chromaticBloom.g > 1e-9) hueSafeScale = min(hueSafeScale, available.g / chromaticBloom.g);
    if (chromaticBloom.b > 1e-9) hueSafeScale = min(hueSafeScale, available.b / chromaticBloom.b);
    vec3 compositeLinear = baseWithNeutral + chromaticBloom * clamp(hueSafeScale, 0.0, 1.0);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * Resurrected from commit 2c51e78 "Preserve color through linear HDR bloom".
 * The first fully-linear composite: pure bracket selection, no neutral/chroma
 * split. Bloom replaces the base rather than adding to it, which is why it
 * needed the 0.30 global strength scale to stay controlled.
 */
const LINEAR_HDR_SHADER = PRELUDE + V1_RISK_FUNCTIONS + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    vec3 raw = linearToSrgb(rawLinear);
    vec3 mid = linearToSrgb(midLinear);
    vec3 high = linearToSrgb(highLinear);
    float highRisk = pixelWhiteMergeRisk(raw, high);
    float midRisk = pixelWhiteMergeRisk(raw, mid);
    float highWeight = 1.0 - v1Smoothstep(0.035, 0.20, highRisk);
    float midWeight = 1.0 - v1Smoothstep(0.05, 0.24, midRisk);
    vec3 upperLinear = mix(midLinear, highLinear, highWeight);
    vec3 bloomCompositeLinear = mix(lowLinear, upperLinear, midWeight);
    vec3 compositeLinear = mix(
        rawLinear,
        bloomCompositeLinear,
        shadowBloomWeight(raw, high)
    );

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * Resurrected from commit 68d2550 "Preserve chromatic bloom without lifting
 * shadows". Takes chroma from the mid bracket and caps neutral + chromatic
 * energy together against one perceptual ceiling, which is the reason it holds
 * black better than linear-hdr.
 */
const CHROMA_CAPPED_SHADER = PRELUDE + V1_RISK_FUNCTIONS + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    vec3 raw = linearToSrgb(rawLinear);
    vec3 mid = linearToSrgb(midLinear);
    vec3 high = linearToSrgb(highLinear);
    float highRisk = pixelWhiteMergeRisk(raw, high);
    float midRisk = pixelWhiteMergeRisk(raw, mid);
    float highWeight = 1.0 - v1Smoothstep(0.035, 0.20, highRisk);
    float midWeight = 1.0 - v1Smoothstep(0.05, 0.24, midRisk);
    vec3 upperLinear = mix(midLinear, highLinear, highWeight);
    vec3 selectedLinear = mix(lowLinear, upperLinear, midWeight);

    vec3 selectedAdded = max(selectedLinear - rawLinear, vec3(0.0));
    float neutralBloom = minChannel(selectedAdded);
    float protectedNeutral = neutralBloom * shadowBloomWeight(raw, high);

    vec3 midAdded = max(midLinear - rawLinear, vec3(0.0));
    float midAddedNeutral = minChannel(midAdded);
    vec3 chromaticBloom = max(midAdded - vec3(midAddedNeutral), vec3(0.0));
    float chromaEnergy = maxChannel(chromaticBloom);

    float chromaGate = v1Smoothstep(
        srgbToLinear(0.02),
        srgbToLinear(0.08),
        chromaEnergy
    );
    float darkMask = 1.0 - v1Smoothstep(0.02, 0.12, maxChannel(raw));
    vec3 addedBloom = vec3(protectedNeutral) + chromaticBloom * chromaGate;
    float addedEnergy = maxChannel(addedBloom);
    float addedLimit = mix(1.0, srgbToLinear(0.18), darkMask);
    float addedScale = addedEnergy > 1e-9
        ? min(1.0, addedLimit / addedEnergy)
        : 0.0;

    vec3 bloomHeadroom = max(vec3(1.0) - rawLinear, vec3(0.0));
    vec3 compositeLinear = rawLinear
        + min(addedBloom * addedScale, bloomHeadroom);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * Targets the degenerate white-highlight condition.
 *
 * Two failures compound on a blown white core in the shipped strategy:
 *
 *  1. `clippedDetail` fires all three of its smoothsteps on a bright achromatic
 *     pixel, so risk saturates and the high bracket is weighted to ~0. Bloom
 *     switches off exactly where it matters most. But the detector exists to
 *     stop bloom from washing *color* out â€” on a pixel whose raw value is
 *     already achromatic there is no hue to protect, so the suppression buys
 *     nothing and costs the halo. Here the clipped-detail term is gated by raw
 *     saturation.
 *  2. Chroma is sourced from `high - raw`. A blown core's high bracket is white
 *     too, so the chroma vector collapses to zero and the halo has no color
 *     left to carry. Here the hue *direction* comes from whichever bracket has
 *     the most chromatic purity (the wider, dimmer brackets still see the
 *     colored surround), while the *energy* still comes from the selected
 *     bracket. Direction and intensity are decoupled.
 */
const WHITE_CORE_CHROMA_SHADER = PRELUDE + /* glsl */`
float chromaPurityOf(vec3 added) {
    float energy = maxChannel(added);
    if (energy < 1e-9) return 0.0;
    return (energy - minChannel(added)) / energy;
}

/** Unit-ish chroma direction: the added colour with its neutral part removed. */
vec3 chromaVector(vec3 added) {
    return max(added - vec3(minChannel(added)), vec3(0.0));
}

float saturationOf(vec3 value) {
    float m = maxChannel(value);
    if (m < 1e-9) return 0.0;
    return (m - minChannel(value)) / m;
}

/**
 * White-merge risk that only fires when there is chroma at stake. The colorWash
 * term already self-cancels on achromatic input; the clippedDetail term does
 * not, so it is scaled by how much saturation the raw pixel actually has.
 */
float chromaAwareRisk(vec3 raw, vec3 bloomed) {
    float rawMax = maxChannel(raw);
    if (rawMax < 0.04) return 0.0;
    float bloomMax = maxChannel(bloomed);
    float bloomMin = minChannel(bloomed);
    float rawSaturation = saturationOf(raw);
    float bloomSaturation = (bloomMax - bloomMin) / max(bloomMax, 1e-9);
    float colorWash = v1Smoothstep(0.72, 0.98, bloomMin)
        * max(rawSaturation - bloomSaturation, 0.0);
    float clippedDetail = v1Smoothstep(0.82, 0.995, bloomMax)
        * v1Smoothstep(0.03, 0.22, bloomMax - rawMax)
        * v1Smoothstep(0.30, 0.85, rawMax)
        * v1Smoothstep(0.04, 0.18, rawSaturation);
    return max(colorWash, clippedDetail * 0.65);
}

float shadowBloomWeight(vec3 raw, vec3 bloomed) {
    float rawMax = maxChannel(raw);
    if (rawMax >= 0.04) return 1.0;
    return v1Smoothstep(0.025, 0.14, maxChannel(bloomed));
}

void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    vec3 raw = linearToSrgb(rawLinear);
    vec3 mid = linearToSrgb(midLinear);
    vec3 high = linearToSrgb(highLinear);
    float highRisk = chromaAwareRisk(raw, high);
    float midRisk = chromaAwareRisk(raw, mid);
    float highWeight = (1.0 - v1Smoothstep(0.035, 0.20, highRisk))
        * mix(1.0, 0.15, globalBloomBias);
    float midWeight = (1.0 - v1Smoothstep(0.05, 0.24, midRisk))
        * mix(1.0, 0.35, globalBloomBias);
    vec3 upperLinear = mix(midLinear, highLinear, highWeight);
    vec3 selectedLinear = mix(lowLinear, upperLinear, midWeight);

    vec3 lowAdded = max(lowLinear - rawLinear, vec3(0.0));
    vec3 midAdded = max(midLinear - rawLinear, vec3(0.0));
    vec3 highAdded = max(highLinear - rawLinear, vec3(0.0));
    vec3 selectedAdded = max(selectedLinear - rawLinear, vec3(0.0));

    float neutralBloom = minChannel(selectedAdded);
    float protectedNeutral = neutralBloom * shadowBloomWeight(raw, high);

    // Hue reference: the bracket that still carries colour. A blown highlight
    // whites out the high bracket first and the low bracket last, so this
    // walks down the stack instead of giving up.
    float highPurity = chromaPurityOf(highAdded);
    float midPurity = chromaPurityOf(midAdded);
    float lowPurity = chromaPurityOf(lowAdded);
    vec3 referenceChroma = chromaVector(highAdded);
    float referencePurity = highPurity;
    if (midPurity > referencePurity) {
        referenceChroma = chromaVector(midAdded);
        referencePurity = midPurity;
    }
    if (lowPurity > referencePurity) {
        referenceChroma = chromaVector(lowAdded);
        referencePurity = lowPurity;
    }
    float referenceEnergy = maxChannel(referenceChroma);
    vec3 chromaDirection = referenceEnergy > 1e-9
        ? referenceChroma / referenceEnergy
        : vec3(0.0);

    // Energy comes from the selected bracket, so intensity still tracks the
    // exposure decision even when the hue came from a dimmer bracket.
    float selectedEnergy = maxChannel(selectedAdded);
    float chromaEnergy = selectedEnergy * referencePurity;
    float sceneChromaScale = mix(1.0, 0.65, globalBloomBias);
    float chromaGate = v1Smoothstep(srgbToLinear(0.015), srgbToLinear(0.07), chromaEnergy)
        * v1Smoothstep(0.05, 0.30, referencePurity)
        * sceneChromaScale;

    float chromaShoulder = srgbToLinear(0.40);
    float mappedChromaEnergy = chromaShoulder
        * (1.0 - exp(-chromaEnergy / max(chromaShoulder, 1e-9)));
    vec3 chromaticBloom = chromaDirection * mappedChromaEnergy * chromaGate;

    float saturationProtection = v1Smoothstep(0.15, 0.65, referencePurity);
    protectedNeutral *= mix(1.0, 0.30, saturationProtection);

    float rawMax = maxChannel(raw);
    float darkMask = 1.0 - v1Smoothstep(0.02, 0.12, rawMax);
    float baseLimitSrgb = mix(0.18, 0.11, globalBloomBias);
    float neutralLimit = mix(1.0, srgbToLinear(baseLimitSrgb), darkMask);
    float neutralHeadroom = max(minChannel(vec3(1.0) - rawLinear), 0.0);
    float neutralAdded = min(min(protectedNeutral, neutralLimit), neutralHeadroom);

    vec3 baseWithNeutral = rawLinear + vec3(neutralAdded);
    vec3 available = max(vec3(1.0) - baseWithNeutral, vec3(0.0));
    float hueSafeScale = 1.0;
    if (chromaticBloom.r > 1e-9) hueSafeScale = min(hueSafeScale, available.r / chromaticBloom.r);
    if (chromaticBloom.g > 1e-9) hueSafeScale = min(hueSafeScale, available.g / chromaticBloom.g);
    if (chromaticBloom.b > 1e-9) hueSafeScale = min(hueSafeScale, available.b / chromaticBloom.b);
    vec3 compositeLinear = baseWithNeutral + chromaticBloom * clamp(hueSafeScale, 0.0, 1.0);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * Sliding-window reactive bloom: no discrete bracket selection and no
 * neutral/chroma split.
 *
 * The three brackets are treated as samples of one continuous exposure curve
 * between a minimum (low) and maximum (high) bloom. A single per-pixel position
 * along that window is chosen from how much headroom the raw pixel has left,
 * and the composite is one interpolation at that point. Where the base is
 * already near clipping the window slides toward the low end, so a blown
 * highlight gets a narrow tight halo instead of the bloom being switched off
 * entirely â€” the failure the discrete selector has on white cores.
 */
const SLIDING_WINDOW_SHADER = PRELUDE + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    vec3 raw = linearToSrgb(rawLinear);
    float rawMax = maxChannel(raw);

    // Window position: 1 = full high bracket, 0 = low bracket only. Headroom
    // drives it, so bright pixels slide down the window continuously rather
    // than falling off a threshold.
    float headroom = 1.0 - v1Smoothstep(0.45, 0.97, rawMax);
    float window = headroom * mix(1.0, 0.45, globalBloomBias);

    // One interpolation across the whole stack: low -> mid over the first half
    // of the window, mid -> high over the second.
    float lowerBlend = clamp(window * 2.0, 0.0, 1.0);
    float upperBlend = clamp(window * 2.0 - 1.0, 0.0, 1.0);
    vec3 windowed = mix(mix(lowLinear, midLinear, lowerBlend), highLinear, upperBlend);

    // Bloom is added light, never a replacement for the sharp base.
    vec3 added = max(windowed - rawLinear, vec3(0.0));

    // Fade added light out in true black so inter-LED gaps keep their contrast.
    float shadowGate = rawMax >= 0.04
        ? 1.0
        : v1Smoothstep(0.025, 0.14, maxChannel(linearToSrgb(windowed)));

    // One uniform-vector shoulder on the whole added colour. Scaling the vector
    // rather than clipping channels is what keeps a saturated halo saturated as
    // it brightens.
    float addedEnergy = maxChannel(added);
    float shoulder = srgbToLinear(mix(0.42, 0.26, globalBloomBias));
    float mappedEnergy = shoulder * (1.0 - exp(-addedEnergy / max(shoulder, 1e-9)));
    float energyScale = addedEnergy > 1e-9 ? mappedEnergy / addedEnergy : 0.0;
    vec3 shaped = added * energyScale * shadowGate;

    // Single hue-safe gamut scale; never clip channels independently.
    vec3 available = max(vec3(1.0) - rawLinear, vec3(0.0));
    float hueSafeScale = 1.0;
    if (shaped.r > 1e-9) hueSafeScale = min(hueSafeScale, available.r / shaped.r);
    if (shaped.g > 1e-9) hueSafeScale = min(hueSafeScale, available.g / shaped.g);
    if (shaped.b > 1e-9) hueSafeScale = min(hueSafeScale, available.b / shaped.b);
    vec3 compositeLinear = rawLinear + shaped * clamp(hueSafeScale, 0.0, 1.0);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * Recovers hue for a blown-out highlight from the region around it.
 *
 * Measurement of `white-core-chroma` showed why gating the white detector was
 * not enough: with all-1 radius scales the three brackets are the same blur at
 * three intensities, so they are near-scalar multiples and every one of them is
 * white at a white core. No selection among them can produce colour that none
 * of them has.
 *
 * This strategy pairs its shader with genuinely different spatial scales
 * (`radiusScales`), which makes the high bracket a wide blur whose value at the
 * core is dominated by the *surrounding* pixels. The annulus estimate
 * `wide - narrow` then isolates that surround: it is the light arriving from
 * around the highlight rather than from the highlight itself, and it still
 * carries the scene's hue when the core has none. Bloom energy stays tied to
 * the narrow brackets so halo size does not balloon.
 */
const WIDE_SURROUND_CHROMA_SHADER = PRELUDE + /* glsl */`
float saturationOf(vec3 value) {
    float m = maxChannel(value);
    if (m < 1e-9) return 0.0;
    return (m - minChannel(value)) / m;
}

void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 narrowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 wideLinear = texture2D(highFrame, vUv).rgb;

    vec3 raw = linearToSrgb(rawLinear);
    float rawMax = maxChannel(raw);
    float rawSaturation = saturationOf(raw);

    vec3 narrowAdded = max(narrowLinear - rawLinear, vec3(0.0));
    vec3 midAdded = max(midLinear - rawLinear, vec3(0.0));
    vec3 wideAdded = max(wideLinear - rawLinear, vec3(0.0));

    // Annulus: light from around this pixel rather than from it. The wide
    // bracket minus the narrow one removes the core's own contribution, which
    // is exactly the part that has gone achromatic on a blown highlight.
    vec3 surround = max(wideAdded - midAdded, vec3(0.0));
    float surroundEnergy = maxChannel(surround);
    vec3 surroundChroma = max(surround - vec3(minChannel(surround)), vec3(0.0));
    float surroundChromaEnergy = maxChannel(surroundChroma);
    float surroundPurity = surroundChromaEnergy / max(surroundEnergy, 1e-9);
    vec3 surroundDirection = surroundChromaEnergy > 1e-9
        ? surroundChroma / surroundChromaEnergy
        : vec3(0.0);

    // Local chroma, used wherever the pixel still has colour of its own.
    vec3 localChroma = max(midAdded - vec3(minChannel(midAdded)), vec3(0.0));
    float localChromaEnergy = maxChannel(localChroma);
    vec3 localDirection = localChromaEnergy > 1e-9
        ? localChroma / localChromaEnergy
        : vec3(0.0);

    // Blend toward the surround exactly where the local signal has lost its
    // hue: bright and desaturated. Elsewhere this is a no-op, so ordinary
    // coloured highlights behave as before.
    float blownOut = v1Smoothstep(0.55, 0.92, rawMax)
        * (1.0 - v1Smoothstep(0.05, 0.22, rawSaturation));
    vec3 chromaDirection = normalize(mix(localDirection, surroundDirection, blownOut)
        + vec3(1e-6));
    float directionPurity = mix(
        localChromaEnergy / max(maxChannel(midAdded), 1e-9),
        surroundPurity,
        blownOut
    );

    // Energy from the narrow brackets so a wide hue reference cannot inflate
    // the halo. Neutral energy is the only part that can drive toward white,
    // so it stays under the global exposure bias.
    float neutralBloom = minChannel(midAdded);
    float sceneScale = mix(1.0, 0.35, globalBloomBias);
    float protectedNeutral = neutralBloom * sceneScale;
    if (rawMax < 0.04) {
        protectedNeutral *= v1Smoothstep(0.025, 0.14, maxChannel(linearToSrgb(midLinear)));
    }

    float chromaEnergy = maxChannel(midAdded) * directionPurity
        * mix(1.0, 0.65, globalBloomBias);
    float chromaShoulder = srgbToLinear(0.40);
    float mappedChromaEnergy = chromaShoulder
        * (1.0 - exp(-chromaEnergy / max(chromaShoulder, 1e-9)));
    float chromaGate = v1Smoothstep(srgbToLinear(0.010), srgbToLinear(0.055), chromaEnergy);
    vec3 chromaticBloom = chromaDirection * mappedChromaEnergy * chromaGate;

    // Saturated results need less neutral lift; blown cores need less still,
    // because neutral energy there is what produced the white in the first
    // place.
    protectedNeutral *= mix(1.0, 0.30, v1Smoothstep(0.15, 0.65, directionPurity));
    protectedNeutral *= mix(1.0, 0.45, blownOut);

    float darkMask = 1.0 - v1Smoothstep(0.02, 0.12, rawMax);
    float baseLimitSrgb = mix(0.18, 0.11, globalBloomBias);
    float neutralLimit = mix(1.0, srgbToLinear(baseLimitSrgb), darkMask);
    float neutralHeadroom = max(minChannel(vec3(1.0) - rawLinear), 0.0);
    float neutralAdded = min(min(protectedNeutral, neutralLimit), neutralHeadroom);

    vec3 baseWithNeutral = rawLinear + vec3(neutralAdded);
    vec3 available = max(vec3(1.0) - baseWithNeutral, vec3(0.0));
    float hueSafeScale = 1.0;
    if (chromaticBloom.r > 1e-9) hueSafeScale = min(hueSafeScale, available.r / chromaticBloom.r);
    if (chromaticBloom.g > 1e-9) hueSafeScale = min(hueSafeScale, available.g / chromaticBloom.g);
    if (chromaticBloom.b > 1e-9) hueSafeScale = min(hueSafeScale, available.b / chromaticBloom.b);
    vec3 compositeLinear = baseWithNeutral + chromaticBloom * clamp(hueSafeScale, 0.0, 1.0);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * wide-surround-chroma, with its blown-core neutral penalty made conditional.
 *
 * The parent strategy suppresses neutral bloom wherever a pixel is bright and
 * desaturated, on the theory that neutral energy is what drove it white. But a
 * genuinely white LED is bright and desaturated by definition, so that penalty
 * also fires on white sources that never washed out — issue #493 failure mode
 * (b). The two-component ocular glare model says the near-halo tracks the
 * source's own chromaticity: a white LED's halo is legitimately white.
 *
 * The penalty is therefore gated on `surroundPurity` — how much hue the
 * surrounding region actually has to offer. Where the surround is colourful,
 * the substitution is real and the neutral penalty still applies. Where the
 * surround is itself neutral, the pixel is genuinely white and keeps its glow.
 */
const SURROUND_WHITE_SAFE_SHADER = PRELUDE + /* glsl */`
float saturationOf(vec3 value) {
    float m = maxChannel(value);
    if (m < 1e-9) return 0.0;
    return (m - minChannel(value)) / m;
}

void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 wideLinear = texture2D(highFrame, vUv).rgb;

    vec3 raw = linearToSrgb(rawLinear);
    float rawMax = maxChannel(raw);
    float rawSaturation = saturationOf(raw);

    vec3 midAdded = max(midLinear - rawLinear, vec3(0.0));
    vec3 wideAdded = max(wideLinear - rawLinear, vec3(0.0));

    vec3 surround = max(wideAdded - midAdded, vec3(0.0));
    float surroundEnergy = maxChannel(surround);
    vec3 surroundChroma = max(surround - vec3(minChannel(surround)), vec3(0.0));
    float surroundChromaEnergy = maxChannel(surroundChroma);
    float surroundPurity = surroundChromaEnergy / max(surroundEnergy, 1e-9);
    vec3 surroundDirection = surroundChromaEnergy > 1e-9
        ? surroundChroma / surroundChromaEnergy
        : vec3(0.0);

    vec3 localChroma = max(midAdded - vec3(minChannel(midAdded)), vec3(0.0));
    float localChromaEnergy = maxChannel(localChroma);
    vec3 localDirection = localChromaEnergy > 1e-9
        ? localChroma / localChromaEnergy
        : vec3(0.0);

    float blownOut = v1Smoothstep(0.55, 0.92, rawMax)
        * (1.0 - v1Smoothstep(0.05, 0.22, rawSaturation));
    // Only borrow the surround's hue when it HAS one. Blending toward a null
    // direction is what silently drained white cores in the parent strategy.
    float surroundRescue = blownOut * v1Smoothstep(0.06, 0.30, surroundPurity);

    vec3 chromaDirection = normalize(mix(localDirection, surroundDirection, surroundRescue)
        + vec3(1e-6));
    float directionPurity = mix(
        localChromaEnergy / max(maxChannel(midAdded), 1e-9),
        surroundPurity,
        surroundRescue
    );

    float neutralBloom = minChannel(midAdded);
    float sceneScale = mix(1.0, 0.35, globalBloomBias);
    float protectedNeutral = neutralBloom * sceneScale;
    if (rawMax < 0.04) {
        protectedNeutral *= v1Smoothstep(0.025, 0.14, maxChannel(linearToSrgb(midLinear)));
    }

    float chromaEnergy = maxChannel(midAdded) * directionPurity
        * mix(1.0, 0.65, globalBloomBias);
    float chromaShoulder = srgbToLinear(0.40);
    float mappedChromaEnergy = chromaShoulder
        * (1.0 - exp(-chromaEnergy / max(chromaShoulder, 1e-9)));
    float chromaGate = v1Smoothstep(srgbToLinear(0.010), srgbToLinear(0.055), chromaEnergy);
    vec3 chromaticBloom = chromaDirection * mappedChromaEnergy * chromaGate;

    protectedNeutral *= mix(1.0, 0.30, v1Smoothstep(0.15, 0.65, directionPurity));
    // Gated on the rescue, not on blownOut: a white core with a white surround
    // keeps its full neutral halo.
    protectedNeutral *= mix(1.0, 0.45, surroundRescue);

    float darkMask = 1.0 - v1Smoothstep(0.02, 0.12, rawMax);
    float baseLimitSrgb = mix(0.18, 0.11, globalBloomBias);
    float neutralLimit = mix(1.0, srgbToLinear(baseLimitSrgb), darkMask);
    float neutralHeadroom = max(minChannel(vec3(1.0) - rawLinear), 0.0);
    float neutralAdded = min(min(protectedNeutral, neutralLimit), neutralHeadroom);

    vec3 baseWithNeutral = rawLinear + vec3(neutralAdded);
    vec3 available = max(vec3(1.0) - baseWithNeutral, vec3(0.0));
    float hueSafeScale = 1.0;
    if (chromaticBloom.r > 1e-9) hueSafeScale = min(hueSafeScale, available.r / chromaticBloom.r);
    if (chromaticBloom.g > 1e-9) hueSafeScale = min(hueSafeScale, available.g / chromaticBloom.g);
    if (chromaticBloom.b > 1e-9) hueSafeScale = min(hueSafeScale, available.b / chromaticBloom.b);
    vec3 compositeLinear = baseWithNeutral + chromaticBloom * clamp(hueSafeScale, 0.0, 1.0);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * The modern display-transform pattern, applied to bloom compositing.
 *
 * No white-merge detector exists here, so none can false-positive on a white
 * pixel. Bloom is accumulated as added light in linear space, then ONE
 * achromatic axis — the max-RGB norm — is tone-compressed and RGB is rebuilt
 * from the untouched channel ratio. Because no channel is ever compressed
 * independently, hue cannot rotate and a colored halo cannot converge to white
 * as it brightens. Desaturation becomes an explicit, bounded "path to white"
 * applied only as the norm approaches display maximum.
 *
 * Follows OpenDRT's max-RGB-norm tonescale + dechroma, Khronos PBR Neutral's
 * hue-invariant shoulder, and ACES 2.0's rule that chroma compression should
 * ease off where purity is already high.
 */
const NORM_TONESCALE_SHADER = PRELUDE + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    // Bloom is added light. Energy-proportional across brackets, never a
    // replacement for the sharp base (Frostbite/COD linear-light discipline).
    vec3 added = max(lowLinear - rawLinear, vec3(0.0)) * 0.45
        + max(midLinear - rawLinear, vec3(0.0)) * 0.35
        + max(highLinear - rawLinear, vec3(0.0)) * 0.30;

    // A halo with no sharp core behind it must not become a scene-wide veil.
    float rawMaxSrgb = maxChannel(linearToSrgb(rawLinear));
    if (rawMaxSrgb < 0.04) {
        added *= v1Smoothstep(0.025, 0.14, maxChannel(linearToSrgb(highLinear)));
    }
    added *= mix(1.0, 0.55, globalBloomBias);

    vec3 scene = rawLinear + added;
    float norm = maxChannel(scene);
    if (norm < 1e-9) {
        gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);
        return;
    }

    // Tone-compress the single norm axis; rebuild colour from the ratio.
    float knee = 0.55;
    float toned = norm <= knee
        ? norm
        : knee + (1.0 - knee) * (1.0 - exp(-(norm - knee) / max(1.0 - knee, 1e-9)));
    vec3 toneMapped = (scene / norm) * toned;

    // Explicit path-to-white: only near display max, and eased off where the
    // colour is already pure so saturated halos resist whitening longest.
    float purity = (norm - minChannel(scene)) / max(norm, 1e-9);
    float dechroma = v1Smoothstep(0.85, 1.60, norm) * mix(0.40, 0.12, purity);
    vec3 finalLinear = mix(toneMapped, vec3(toned), dechroma);

    gl_FragColor = vec4(clamp(linearToSrgb(finalLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * surround-white-safe, plus an explicit glow allowance for neutral sources.
 *
 * Round 2 measured that the surround gate alone barely moves this content: the
 * energy that actually starves a white highlight is the global one. In a bright
 * scene `sceneScale` cuts ALL neutral bloom to 35%, and neutral energy is the
 * only bloom a white LED can have — a coloured LED still has its chroma path.
 * The global exposure control is therefore applied asymmetrically: it keeps
 * full authority over coloured pixels (where runaway neutral energy is what
 * drives hue to white) and relaxes for bright neutral sources, whose halo is
 * legitimately white. Bounded by `rawMax`, so shadows are untouched.
 */
const SURROUND_WHITE_GLOW_SHADER = PRELUDE + /* glsl */`
float saturationOf(vec3 value) {
    float m = maxChannel(value);
    if (m < 1e-9) return 0.0;
    return (m - minChannel(value)) / m;
}

void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 wideLinear = texture2D(highFrame, vUv).rgb;

    vec3 raw = linearToSrgb(rawLinear);
    float rawMax = maxChannel(raw);
    float rawSaturation = saturationOf(raw);

    vec3 midAdded = max(midLinear - rawLinear, vec3(0.0));
    vec3 wideAdded = max(wideLinear - rawLinear, vec3(0.0));

    vec3 surround = max(wideAdded - midAdded, vec3(0.0));
    float surroundEnergy = maxChannel(surround);
    vec3 surroundChroma = max(surround - vec3(minChannel(surround)), vec3(0.0));
    float surroundChromaEnergy = maxChannel(surroundChroma);
    float surroundPurity = surroundChromaEnergy / max(surroundEnergy, 1e-9);
    vec3 surroundDirection = surroundChromaEnergy > 1e-9
        ? surroundChroma / surroundChromaEnergy
        : vec3(0.0);

    vec3 localChroma = max(midAdded - vec3(minChannel(midAdded)), vec3(0.0));
    float localChromaEnergy = maxChannel(localChroma);
    vec3 localDirection = localChromaEnergy > 1e-9
        ? localChroma / localChromaEnergy
        : vec3(0.0);

    float blownOut = v1Smoothstep(0.55, 0.92, rawMax)
        * (1.0 - v1Smoothstep(0.05, 0.22, rawSaturation));
    float surroundRescue = blownOut * v1Smoothstep(0.06, 0.30, surroundPurity);

    vec3 chromaDirection = normalize(mix(localDirection, surroundDirection, surroundRescue)
        + vec3(1e-6));
    float directionPurity = mix(
        localChromaEnergy / max(maxChannel(midAdded), 1e-9),
        surroundPurity,
        surroundRescue
    );

    // A bright, low-saturation SOURCE pixel: a white LED, not a washed-out one.
    float neutralSource = v1Smoothstep(0.22, 0.62, rawMax)
        * (1.0 - v1Smoothstep(0.05, 0.20, rawSaturation));

    float neutralBloom = minChannel(midAdded);
    // Relax the global exposure cut for genuinely white sources only.
    float sceneScale = mix(mix(1.0, 0.35, globalBloomBias), 1.0, neutralSource * 0.80);
    float protectedNeutral = neutralBloom * sceneScale;
    if (rawMax < 0.04) {
        protectedNeutral *= v1Smoothstep(0.025, 0.14, maxChannel(linearToSrgb(midLinear)));
    }

    float chromaEnergy = maxChannel(midAdded) * directionPurity
        * mix(1.0, 0.65, globalBloomBias);
    float chromaShoulder = srgbToLinear(0.40);
    float mappedChromaEnergy = chromaShoulder
        * (1.0 - exp(-chromaEnergy / max(chromaShoulder, 1e-9)));
    float chromaGate = v1Smoothstep(srgbToLinear(0.010), srgbToLinear(0.055), chromaEnergy);
    vec3 chromaticBloom = chromaDirection * mappedChromaEnergy * chromaGate;

    protectedNeutral *= mix(1.0, 0.30, v1Smoothstep(0.15, 0.65, directionPurity));
    protectedNeutral *= mix(1.0, 0.45, surroundRescue);

    float darkMask = 1.0 - v1Smoothstep(0.02, 0.12, rawMax);
    // The neutral ceiling also has to lift for a white source, or the glow is
    // restored by sceneScale and then immediately clamped away again.
    float baseLimitSrgb = mix(mix(0.18, 0.11, globalBloomBias), 0.30, neutralSource);
    float neutralLimit = mix(1.0, srgbToLinear(baseLimitSrgb), darkMask);
    float neutralHeadroom = max(minChannel(vec3(1.0) - rawLinear), 0.0);
    float neutralAdded = min(min(protectedNeutral, neutralLimit), neutralHeadroom);

    vec3 baseWithNeutral = rawLinear + vec3(neutralAdded);
    vec3 available = max(vec3(1.0) - baseWithNeutral, vec3(0.0));
    float hueSafeScale = 1.0;
    if (chromaticBloom.r > 1e-9) hueSafeScale = min(hueSafeScale, available.r / chromaticBloom.r);
    if (chromaticBloom.g > 1e-9) hueSafeScale = min(hueSafeScale, available.g / chromaticBloom.g);
    if (chromaticBloom.b > 1e-9) hueSafeScale = min(hueSafeScale, available.b / chromaticBloom.b);
    vec3 compositeLinear = baseWithNeutral + chromaticBloom * clamp(hueSafeScale, 0.0, 1.0);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * norm-tonescale with the veil closed.
 *
 * Round 2 measured the unguarded version lifting 64% of genuinely dark pixels
 * and dropping saturation to 0.38. Both come from the same cause: a
 * zero-threshold bloom pass deposits *neutral* energy everywhere, which floods
 * shadows and raises every pixel's min channel (destroying purity before the
 * tonescale ever runs). The norm tonescale is kept — it is what prevents hue
 * rotation at the bright end — but the neutral component of added light is now
 * attenuated by how much sharp light actually stands behind the pixel, which
 * is the one thing the unguarded version had no opinion about.
 */
const NORM_TONESCALE_GUARDED_SHADER = PRELUDE + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    vec3 added = max(lowLinear - rawLinear, vec3(0.0)) * 0.45
        + max(midLinear - rawLinear, vec3(0.0)) * 0.35
        + max(highLinear - rawLinear, vec3(0.0)) * 0.30;

    float rawMax = maxChannel(linearToSrgb(rawLinear));

    // Split added light. Chromatic residual is what makes a halo read as
    // coloured and can never push a pixel toward white, so it passes freely.
    // Shared neutral energy is the veil-former and the whitening agent, so it
    // is the only part gated by how lit this pixel already is.
    float addedNeutral = minChannel(added);
    vec3 addedChroma = max(added - vec3(addedNeutral), vec3(0.0));
    float neutralGate = v1Smoothstep(0.02, 0.30, rawMax);
    vec3 guardedAdded = addedChroma + vec3(addedNeutral * neutralGate);
    guardedAdded *= mix(1.0, 0.55, globalBloomBias);

    vec3 scene = rawLinear + guardedAdded;
    float norm = maxChannel(scene);
    if (norm < 1e-9) {
        gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);
        return;
    }

    float knee = 0.55;
    float toned = norm <= knee
        ? norm
        : knee + (1.0 - knee) * (1.0 - exp(-(norm - knee) / max(1.0 - knee, 1e-9)));
    vec3 toneMapped = (scene / norm) * toned;

    float purity = (norm - minChannel(scene)) / max(norm, 1e-9);
    float dechroma = v1Smoothstep(0.85, 1.60, norm) * mix(0.40, 0.12, purity);
    vec3 finalLinear = mix(toneMapped, vec3(toned), dechroma);

    gl_FragColor = vec4(clamp(linearToSrgb(finalLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * norm-tonescale-guarded, retuned for LED-core contrast.
 *
 * The guarded version's one measured weakness against the surround family was
 * core similarity: its widest bracket carries the most energy at the lowest
 * spatial frequency, which softens the sharp LED dot it sits on. Weight shifts
 * toward the tight bracket and the tonescale knee moves up, so midtones pass
 * through linearly and only true highlights roll off.
 */
const NORM_TONESCALE_SHARP_SHADER = PRELUDE + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    vec3 added = max(lowLinear - rawLinear, vec3(0.0)) * 0.55
        + max(midLinear - rawLinear, vec3(0.0)) * 0.30
        + max(highLinear - rawLinear, vec3(0.0)) * 0.20;

    float rawMax = maxChannel(linearToSrgb(rawLinear));
    float addedNeutral = minChannel(added);
    vec3 addedChroma = max(added - vec3(addedNeutral), vec3(0.0));
    float neutralGate = v1Smoothstep(0.02, 0.30, rawMax);
    vec3 guardedAdded = addedChroma + vec3(addedNeutral * neutralGate);
    guardedAdded *= mix(1.0, 0.55, globalBloomBias);

    vec3 scene = rawLinear + guardedAdded;
    float norm = maxChannel(scene);
    if (norm < 1e-9) {
        gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);
        return;
    }

    float knee = 0.68;
    float toned = norm <= knee
        ? norm
        : knee + (1.0 - knee) * (1.0 - exp(-(norm - knee) / max(1.0 - knee, 1e-9)));
    vec3 toneMapped = (scene / norm) * toned;

    float purity = (norm - minChannel(scene)) / max(norm, 1e-9);
    float dechroma = v1Smoothstep(0.85, 1.60, norm) * mix(0.40, 0.12, purity);
    vec3 finalLinear = mix(toneMapped, vec3(toned), dechroma);

    gl_FragColor = vec4(clamp(linearToSrgb(finalLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * The two round-3 winners combined.
 *
 * norm-tonescale-guarded prevents whitening on the way up; the surround family
 * repairs a core that arrived already white in the source. They address
 * different halves of the problem, so this borrows the annulus hue reference
 * and applies it to the norm tonescale's channel ratio — brightness still
 * comes from the tone-compressed norm, only the hue is rotated, and only where
 * the pixel is blown out and the surround actually has a hue to lend.
 */
const NORM_SURROUND_HUE_SHADER = PRELUDE + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    vec3 midAdded = max(midLinear - rawLinear, vec3(0.0));
    vec3 highAdded = max(highLinear - rawLinear, vec3(0.0));

    vec3 added = max(lowLinear - rawLinear, vec3(0.0)) * 0.45
        + midAdded * 0.35
        + highAdded * 0.30;

    float rawMax = maxChannel(linearToSrgb(rawLinear));
    float addedNeutral = minChannel(added);
    vec3 addedChroma = max(added - vec3(addedNeutral), vec3(0.0));
    float neutralGate = v1Smoothstep(0.02, 0.30, rawMax);
    vec3 guardedAdded = addedChroma + vec3(addedNeutral * neutralGate);
    guardedAdded *= mix(1.0, 0.55, globalBloomBias);

    vec3 scene = rawLinear + guardedAdded;
    float norm = maxChannel(scene);
    if (norm < 1e-9) {
        gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);
        return;
    }

    // Annulus hue: light from around the pixel, with the core's own (already
    // achromatic) contribution removed.
    vec3 surround = max(highAdded - midAdded, vec3(0.0));
    float surroundEnergy = maxChannel(surround);
    float surroundPurity = surroundEnergy > 1e-9
        ? (surroundEnergy - minChannel(surround)) / surroundEnergy
        : 0.0;
    float rawSaturation = maxChannel(rawLinear) > 1e-9
        ? (maxChannel(rawLinear) - minChannel(rawLinear)) / maxChannel(rawLinear)
        : 0.0;
    float blownOut = v1Smoothstep(0.55, 0.92, rawMax)
        * (1.0 - v1Smoothstep(0.05, 0.22, rawSaturation));
    float rescue = blownOut * v1Smoothstep(0.06, 0.30, surroundPurity) * 0.6;

    vec3 sceneRatio = scene / norm;
    vec3 surroundRatio = surroundEnergy > 1e-9 ? surround / surroundEnergy : sceneRatio;
    // Brightness stays with the norm; only the ratio (hue) is borrowed.
    vec3 ratio = mix(sceneRatio, surroundRatio, rescue);

    float knee = 0.55;
    float toned = norm <= knee
        ? norm
        : knee + (1.0 - knee) * (1.0 - exp(-(norm - knee) / max(1.0 - knee, 1e-9)));
    vec3 toneMapped = ratio * toned;

    float purity = (norm - minChannel(scene)) / max(norm, 1e-9);
    float dechroma = v1Smoothstep(0.85, 1.60, norm) * mix(0.40, 0.12, purity);
    vec3 finalLinear = mix(toneMapped, vec3(toned), dechroma);

    gl_FragColor = vec4(clamp(linearToSrgb(finalLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * The legacy look, reconstructed as a reference tile.
 *
 * Plain additive bloom with a per-channel clamp — the pre-HDR composite whose
 * diffusion response the frosted-acrylic directive (#493) names as the target:
 * glow grows steeply with drive level and a fully driven region whites out.
 * It also reproduces the legacy defect on purpose: past threshold, a pure
 * red/green/blue core overflows, the saturated channels clip first, and the
 * residue turns white. Kept so every acrylic candidate can be A/B'd against
 * the look it is supposed to match-except-for-the-defect.
 */
const LEGACY_ADDITIVE_SHADER = PRELUDE + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    vec3 added = max(lowLinear - rawLinear, vec3(0.0)) * 0.50
        + max(midLinear - rawLinear, vec3(0.0)) * 0.40
        + max(highLinear - rawLinear, vec3(0.0)) * 0.35;
    added *= mix(1.0, 0.55, globalBloomBias);

    // Per-channel clamp: the defect under study, preserved faithfully.
    vec3 compositeLinear = min(rawLinear + added, vec3(1.0));
    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * The frosted-acrylic diffuser composite (#493 revised directive).
 *
 * Keeps legacy bloom's energy and spatial response; changes only what happens
 * past the threshold brightness. Overflow is never clipped per channel —
 * the pixel's hue ratio is held fixed, and as local drive approaches full the
 * wide scatter lobe is fed extra energy, so excess light goes OUTWARD into
 * diffusion instead of UPWARD into clipping. A blown red LED floods a wide
 * red glow; a blown white region whites out; same mechanism, no special case.
 * True shadows keep a low-energy gate so isolated dark panel stays black,
 * while gaps inside a hot region fill in — which is exactly the white-out.
 */
const ACRYLIC_OVERFLOW_SHADER = PRELUDE + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    vec3 highAdded = max(highLinear - rawLinear, vec3(0.0));
    vec3 added = max(lowLinear - rawLinear, vec3(0.0)) * 0.50
        + max(midLinear - rawLinear, vec3(0.0)) * 0.40
        + highAdded * 0.35;
    added *= mix(1.0, 0.55, globalBloomBias);

    // Neutral/chroma split as in norm-tonescale-guarded: chroma passes
    // freely, neutral energy is the veil-former. But the acrylic model needs
    // the gate OPEN inside hot regions — gaps between fully driven LEDs must
    // fill (that IS the white-out) — so litness is extended by hot-region
    // membership, read from the wide lobe's magnitude.
    float rawMax = maxChannel(linearToSrgb(rawLinear));
    float addedNeutral = minChannel(added);
    vec3 addedChroma = max(added - vec3(addedNeutral), vec3(0.0));
    // Hot-region membership opens the neutral gate only where the local glow
    // is itself neutral: a white region's gaps fill white (the white-out),
    // while a red region's gaps are filled by addedChroma alone and stay red.
    float wideMax = maxChannel(highAdded);
    float widePurity = wideMax > 1e-9
        ? (wideMax - minChannel(highAdded)) / wideMax
        : 0.0;
    float hotRegion = v1Smoothstep(0.45, 0.85, maxChannel(linearToSrgb(highLinear)))
        * (1.0 - v1Smoothstep(0.25, 0.60, widePurity));
    float neutralGate = max(v1Smoothstep(0.02, 0.30, rawMax), hotRegion);
    vec3 scene = rawLinear + addedChroma + vec3(addedNeutral * neutralGate);
    float norm = maxChannel(scene);

    // Diffuser flare: past the threshold brightness, pour extra energy in.
    // Magnitude comes from the wide lobe; DIRECTION is the pixel's own hue
    // ratio, so a blown red core flares red rather than the lobe's mixture.
    float flare = v1Smoothstep(0.70, 1.35, norm);
    if (norm > 1e-9) {
        scene += (scene / norm) * wideMax * flare * 0.9;
    }
    norm = maxChannel(scene);

    if (norm < 1e-9) {
        gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);
        return;
    }

    // Hue-locked limiting instead of the legacy per-channel clamp: a soft
    // shoulder on the single norm axis, RGB rebuilt from the untouched ratio.
    float knee = 0.80;
    float toned = norm <= knee
        ? norm
        : knee + (1.0 - knee) * (1.0 - exp(-(norm - knee) / max(1.0 - knee, 1e-9)));
    vec3 compositeLinear = (scene / norm) * min(toned, 1.0);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * acrylic-overflow plus the pane mechanism (#493, round 6).
 *
 * acrylic-overflow fills the gaps between LEDs but leaves the sharp cores
 * fully distinct, so a fully driven region still reads as bright dots on a
 * glowing field rather than one pane. Physically the diffuser blurs the
 * cores exactly as much as it feeds the gaps — the pane IS the cores and
 * gaps converging on the same transmitted field. So inside hot regions this
 * strategy also blends the base itself toward the mid-bracket field
 * (drive-dependent core softening). Dim and mid content keeps its sharp
 * base: the softening is gated by the same purity-conditional hot-region
 * signal as the neutral gap fill, so it engages only where the directive
 * wants dots to merge.
 */
const ACRYLIC_PANE_SHADER = PRELUDE + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    // The bloom operation was right all along; the display transform was
    // wrong (user insight, #493). So: pure additive HDR bloom — per-LED
    // Gaussian splats, energy conserving, no gates, no max(), values free to
    // exceed 1 — followed by ONE hue-locked tone curve on the norm axis.
    // Splat-weighted lobes: the tight lobe is the body of each LED's glow,
    // the wide lobes are faint tails.
    // Wide lobe nearly muted: it is the only carrier that reaches dark
    // neighborhoods (the T4 veil), while the splat body and halo skirts live
    // in the tight and mid lobes. Cutting it beats strengthening the toe,
    // which killed the white peak's skirt at every strength tried.
    vec3 lowAdded = max(lowLinear - rawLinear, vec3(0.0));
    // Low-resolution shadow mask (user direction, 2026-08-24): in deep-
    // contrast content the LOW-FREQUENCY lobes poison the black floor —
    // measured: a source with 20% true blacks rendered with zero pixels
    // under 8 luma while the minimal-bloom reference kept them. The tight
    // lobe's pure blur component is smooth at dot scale (no ring risk) and
    // low wherever the local neighborhood is genuinely dark, so it gates the
    // mid/wide lobes: deep shadows keep only the tight splat skirt, driven
    // regions keep the full stack (their tight field is hot, mask ~ 1).
    float nearDrive = maxChannel(linearToSrgb(lowAdded * 3.0));
    // Band raised (0.16 -> 0.30): UnrealBloom's 'tight' bracket still
    // carries the full five-mip pyramid, whose far tail otherwise opens the
    // mask from across the frame (measured: a bright starburst center
    // flooding perimeter blacks through this exact path).
    // Softened (0.34 -> 0.24 onset): the first cut was too harsh — glow
    // died too abruptly at pool borders (user review of the dataset run).
    // Wide, gradual band: the harshness was the ABRUPT transition, not the
    // pool depth — onset eased to 0.26 but full glow only by 0.72, so the
    // cut is a long gentle ramp while deep pools stay defended.
    float shadowMask = v1Smoothstep(0.26, 0.72, nearDrive);
    vec3 added = lowAdded * 0.70
        + (max(midLinear - rawLinear, vec3(0.0)) * 0.29
            + max(highLinear - rawLinear, vec3(0.0)) * 0.14) * shadowMask;
    // The tight bracket still carries the same five-mip far tail (UnrealBloom
    // structure), so deep-shadow pools also attenuate the whole stack: an
    // extreme bright center otherwise lifts frame corners through the tight
    // bracket alone (measured +28 luma P5 at the starburst frame).
    // Bias-scaled: the brighter the frame, the harder its mip tails flood,
    // so deep-shadow pools defend proportionally (physical acrylic scatters
    // at pitch scale — frame-wide spread is kernel artifact, not physics).
    // Dark-frame floor gentler (0.15 -> 0.38): a dim frame's spill is weak
    // by construction, and the white peak's halo skirt lives in pool
    // territory of exactly such frames (G1 measured 42 -> 0.96 at 0.15).
    // Bias slope softened (dark end 0.38, bright end 0.06): the steeper
    // slope amplified frame-to-frame bias jitter into steady-scene flicker
    // (G3 2.4 > 2.0). Bright-frame pools still defend (starburst delta
    // holds inside the G6 bound).
    added *= mix(mix(0.46, 0.12, globalBloomBias), 1.0, shadowMask);

    // Chroma guard at lit LED cores. The restrained third mip is useful in
    // negative space, but its mid-frequency field can still land blue/cyan
    // energy on a red or magenta core. Preserve bloom parallel to the core's
    // own RGB direction and attenuate only the hue-disagreeing remainder.
    // Gaps have rawLinear == 0, so their newly restored neighbour fill is
    // untouched; neutral and low-purity cores also bypass the guard.
    float coreMax = maxChannel(rawLinear);
    if (coreMax > 1e-6) {
        float corePurity = 1.0 - minChannel(rawLinear) / coreMax;
        float coreDrive = v1Smoothstep(0.06, 0.30, maxChannel(linearToSrgb(rawLinear)));
        float chromaGuard = v1Smoothstep(0.25, 0.65, corePurity) * coreDrive;
        vec3 coreDirection = rawLinear / coreMax;
        float parallelAmount = dot(added, coreDirection)
            / max(dot(coreDirection, coreDirection), 1e-6);
        vec3 parallelBloom = max(parallelAmount, 0.0) * coreDirection;
        vec3 guardedBloom = parallelBloom + (added - parallelBloom) * 0.20;
        added = max(mix(added, guardedBloom, chromaGuard), vec3(0.0));
    }

    // Phase 0 of #496 removed the iris-inversion gain that used to live
    // here: it was compensating for the production profile's 4x strength
    // handicap, which is gone. Capture strength is now trusted.
    vec3 scene = rawLinear + added;
    float norm = maxChannel(scene);
    if (norm < 1e-9) {
        gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);
        return;
    }

    // Tone curve, norm domain, hue-locked (ratio rebuilt after):
    //  - TOE crushes faint spill quadratically — this replaces every veil
    //    gate we ever wrote, smoothly, so dark panel stays black and no seam
    //    can exist;
    //  - linear middle;
    //  - SHOULDER rolls accumulated HDR energy into the display ceiling —
    //    neutral light whites out, colored light saturates in its own hue.
    // Adaptive toe driven by GLOBAL brightness (visual adaptation): in a
    // dark frame the eye/panel shows faint halos (weak toe — the lone white
    // peak keeps its skirt), in a bright frame faint spill reads as veil and
    // gets crushed (strong toe). Uniform per frame, so it cannot seam.
    // Shadow-adaptive toe, driven by the SAME smooth mask as the lobe gate
    // (one mask, no seams): genuinely dark neighborhoods get a strong toe
    // that crushes residual skirt spill back to black, driven regions keep
    // the weak toe that every bright-side gate calibrated (p0b A/B).
    // Adaptive toe REINSTATED (v2): the banding attributed to it turned out
    // to be the untagged-color bt601 mis-decode (user re-diagnosis after the
    // tag fix); with correct bt709 tagging plus the output dither, the
    // spatially-varying toe is clean. Pools get a strong toe that puts their
    // floor at the reference level, driven regions keep the calibrated weak
    // toe. Same smooth mask as the lobe attenuation — one mask, no seams.
    float toeK = mix(0.047, 0.014, shadowMask);
    float toned = (norm * norm) / (norm + toeK);
    // Bloom only ever ADDS: the curve must never take a pixel below its own
    // sharp core (the pool toe was crushing dim LED cores to ~5% of the
    // reference — a destructive tile G5 rightly rejects). Binding only
    // inside cores, where output = raw = reference; gaps have raw ~ 0.
    toned = max(toned, min(norm, maxChannel(rawLinear)));
    float knee = 0.80;
    toned = toned <= knee
        ? toned
        : knee + (1.0 - knee) * (1.0 - exp(-(toned - knee) / max(1.0 - knee, 1e-9)));
    vec3 compositeLinear = (scene / norm) * min(toned, 1.0);
    // Hunt-effect chroma hold at high drive (both AI picture evaluators
    // flagged saturated orange bleaching to cream as full drive accumulates
    // neutral energy): restore the chroma vector as the norm approaches the
    // ceiling. Hue-safe — the chroma vector scales uniformly.
    float driveLift = v1Smoothstep(0.55, 1.0, toned);
    float ceilNeutral = minChannel(compositeLinear);
    vec3 ceilChroma = compositeLinear - vec3(ceilNeutral);
    // Purity gate (both round-2 AI evaluators flagged a lavender cast at
    // whited-out cores): boosting the chroma of a near-neutral pixel tints
    // noise. Only meaningfully colored pixels get the Hunt hold; true white
    // stays white.
    float ceilPurity = maxChannel(ceilChroma) / max(maxChannel(compositeLinear), 1e-6);
    driveLift *= v1Smoothstep(0.08, 0.22, ceilPurity);
    compositeLinear = vec3(ceilNeutral) + ceilChroma * (1.0 + 0.35 * driveLift);

    // Deterministic 4x4 ordered dither at the quantization boundary:
    // crushed shadow gradients otherwise collapse into visible 8-bit bands.
    // +-0.5/255 in display space, hue-neutral, reproducible frame to frame.
    vec2 cell = floor(mod(gl_FragCoord.xy, 4.0));
    float bayer = mod(cell.x * 5.0 + cell.y * 3.0 + cell.x * cell.y, 16.0) / 16.0;
    vec3 display = clamp(linearToSrgb(compositeLinear), 0.0, 1.0);
    display += (bayer - 0.5) / 255.0;

    gl_FragColor = vec4(clamp(display, 0.0, 1.0), 1.0);
}
`;

/**
 * The physically-grounded acrylic model (#493, round 7).
 *
 * The optics literature (Spencer '95 glare; Talvala '07 veiling glare; the
 * photographic star-size law) says a diffuser's kernel is INTENSITY-
 * INDEPENDENT: "diffusion grows with drive level" is an emergent effect of a
 * fixed, wide-tailed linear PSF whose dim tails cross the visible threshold
 * farther out as the source brightens, with apparent radius growing roughly
 * with log(intensity). The drive-dependent gates and flare terms of the
 * earlier acrylic strategies approximate this; here the mechanism is the real
 * one:
 *
 * - a fixed three-Gaussian kernel (the brackets at radius scales 1/1.6/3.2)
 *   with physically dim tails (weights fall off with radius);
 * - pure linear superposition, no drive-dependent gates — a fully driven
 *   region's gaps receive enough summed neighbor spill to saturate (the
 *   white-out emerges), dim content's spill stays faint by linearity;
 * - one true-shadow guard so panel with no local emission stays black; and
 * - hue-locked norm limiting at the display boundary, which converts the
 *   linear overflow into the clipped-pane look without rotating hue.
 */
const ACRYLIC_PSF_SHADER = PRELUDE + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    // Fixed PSF: narrow core lobe, mid lobe, wide dim tail. Linear, no gates.
    vec3 spill = max(lowLinear - rawLinear, vec3(0.0)) * 0.55
        + max(midLinear - rawLinear, vec3(0.0)) * 0.30
        + max(highLinear - rawLinear, vec3(0.0)) * 0.18;
    spill *= mix(1.0, 0.55, globalBloomBias);

    // True-shadow guard: with no meaningful local emission the acrylic is
    // dark. This is the only nonlinearity before the display boundary.
    float rawMax = maxChannel(linearToSrgb(rawLinear));
    if (rawMax < 0.04) {
        spill *= v1Smoothstep(0.030, 0.11, maxChannel(linearToSrgb(highLinear)));
    }

    vec3 scene = rawLinear + spill;
    float norm = maxChannel(scene);
    if (norm < 1e-9) {
        gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);
        return;
    }

    // Display boundary: hue-locked soft clip. Mostly linear until near max so
    // the emergent threshold behavior of the PSF tails is preserved.
    float knee = 0.92;
    float toned = norm <= knee
        ? norm
        : knee + (1.0 - knee) * (1.0 - exp(-(norm - knee) / max(1.0 - knee, 1e-9)));
    vec3 compositeLinear = (scene / norm) * min(toned, 1.0);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * The owned-pipeline acrylic composite (#493, round 9).
 *
 * Consumes the custom PSF pipeline's vec4(emission, coverage) brackets
 * (acrylic-psf-gpu.ts) instead of UnrealBloom RGB blurs. Coverage is what the
 * old pipeline structurally lacked: dividing blurred emission by blurred
 * coverage gives the true average color/brightness of nearby lit panel,
 * undiluted by the black gaps — so the glow field has no rim dip (rings are
 * impossible by construction), halo hue is the real local hue, and the
 * pane/white-out reads from genuine lit-area density rather than luminance
 * proxies. Energy admission keeps the fixed-PSF visibility-threshold physics:
 * the ENERGY field decides where glow shows, the NORMALIZED field decides
 * what it looks like.
 */
const ACRYLIC_NATIVE_SHADER = PRELUDE + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec4 lowField = texture2D(lowFrame, vUv);
    vec4 midField = texture2D(midFrame, vUv);
    vec4 highField = texture2D(highFrame, vUv);

    // Energy: spread emission, scaled by the strategy-owned strength uniform
    // (brackets are pure fields; nothing was baked in at capture).
    vec3 energy = (lowField.rgb * 0.50 + midField.rgb * 0.40 + highField.rgb * 0.35)
        * bloomStrength;
    float energyMax = maxChannel(linearToSrgb(energy));

    // Normalized field: average color/brightness of nearby lit panel,
    // undiluted by black gaps. Weighted toward the tight lobes so local hue
    // dominates, with the wide lobe contributing reach.
    // Hue comes from the TIGHT lobes only: a halo should carry the hue of
    // the LEDs it surrounds, and the 1/8-res wide lobe mixes half the panel
    // toward neutral (measured as S1 0.13 in native2). The wide lobe still
    // contributes energy and reach below.
    vec3 emissionSum = lowField.rgb * 0.70 + midField.rgb * 0.30;
    float coverageSum = lowField.a * 0.70 + midField.a * 0.30;
    vec3 litColor = emissionSum / max(coverageSum, 1e-3);

    // Heat: bright lit color AND a densely lit neighborhood. Coverage must
    // come from the WIDE lobe — the tight lobes see a dense grid as ~25%
    // covered (the dot duty cycle), which kept heat at zero and strangled
    // all glow in bright scenes (native3 frames: crisp dots, black gaps).
    float heat = v1Smoothstep(0.35, 0.85, maxChannel(linearToSrgb(litColor)))
        * v1Smoothstep(0.30, 0.75, highField.a);

    // Chroma restoration (transplanted from acrylic-pane r13): spatial mixing
    // averages neighboring hues toward neutral, which turned bright scenes
    // milky in first light. Boost the chroma vector, thin the shared neutral
    // outside hot regions, keep full neutral inside them (the white-out).
    float litNeutral = minChannel(litColor);
    vec3 litChroma = litColor - vec3(litNeutral);
    litColor = vec3(litNeutral * mix(0.55, 1.0, heat)) + litChroma * 1.55;

    // Iris inversion: the metering collapses capture strength as the frame
    // brightens; invert it inside genuinely hot, dense regions.
    energy *= 1.0 + 1.8 * globalBloomBias * heat;
    energyMax = maxChannel(linearToSrgb(energy));

    // Visibility-threshold admission on ENERGY; appearance from the
    // normalized field. The glow tracks energy amplitude linearly until it
    // reaches the true lit color (its physical ceiling) — the early clamp of
    // first light flattened every gap onto the ceiling and read as milk.
    float admit = v1Smoothstep(0.012, 0.14, energyMax)
        * mix(0.80, 1.0, heat);
    vec3 glow = litColor * admit * clamp(
        maxChannel(energy) / max(maxChannel(litColor) * 0.75, 1e-4), 0.0, 1.0);

    vec3 scene = max(rawLinear, glow);
    float norm = maxChannel(scene);
    if (norm < 1e-9) {
        gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);
        return;
    }

    float knee = 0.80;
    float toned = norm <= knee
        ? norm
        : knee + (1.0 - knee) * (1.0 - exp(-(norm - knee) / max(1.0 - knee, 1e-9)));
    vec3 compositeLinear = (scene / norm) * min(toned, 1.0);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * The #496 Phase-2 reference composite, on the owned PSF pipeline.
 *
 * Iris-free world: capture strength is a fixed geometry treatment, so the
 * composite owns exposure entirely. Structure:
 *  - pure additive HDR splats from the owned pipeline's emission fields
 *    (unclamped, equal-weight-per-channel blurs, splat-weighted lobes);
 *  - COVERAGE admission — the drive-independent veil control the amplitude
 *    toe could never be: glow shows where lit panel exists nearby (so driven
 *    regions merge and halos live at any brightness) and is suppressed where
 *    the neighborhood is unlit (so dark panel stays black at any strength).
 *    Coverage is a blur, so admission cannot ring;
 *  - one hue-locked tone map on the norm axis (small toe + shoulder), RGB
 *    rebuilt from the untouched ratio.
 */
const HDR_REFERENCE_SHADER = PRELUDE + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec4 lowField = texture2D(lowFrame, vUv);
    vec4 midField = texture2D(midFrame, vUv);
    vec4 highField = texture2D(highFrame, vUv);

    vec3 added = (lowField.rgb * 0.55 + midField.rgb * 0.32 + highField.rgb * 0.13)
        * bloomStrength * 4.2;
    // ADMISSION coverage uses only the deep lobes: the tight lobe's alpha
    // still carries per-dot structure at 1/2 res, and admitting on it
    // reintroduced rings (0.63 flagged) — the one thing this architecture
    // must never do. The 1/4 and 1/8 res lobes are smooth at dot scale.
    float coverage = midField.a * 0.45 + highField.a * 0.55;
    float addedMax = maxChannel(linearToSrgb(added));
    // Measured scale (coverage diagnostic on the fully driven sun frame):
    // panel interior sits at 0.16-0.30, p50 0.196 — the alpha dilutes through
    // the pyramid by the dot duty cycle. The band must saturate by ~0.16.
    // Admission: lit-neighborhood (drive-weighted coverage) OR strong light
    // (amplitude escape — the fixed-PSF visibility threshold). The escape is
    // what lets an isolated blazing source keep its halo skirt: its coverage
    // is tiny (small area) but its spill amplitude is high, while dim-driven
    // veil zones have low amplitude AND low coverage.
    float admit = max(v1Smoothstep(0.10, 0.22, coverage),
        v1Smoothstep(0.06, 0.20, addedMax));

    vec3 scene = rawLinear + added * admit;
    float norm = maxChannel(scene);
    if (norm < 1e-9) {
        gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);
        return;
    }

    float toeK = 0.010;
    float toned = (norm * norm) / (norm + toeK);
    float knee = 0.80;
    toned = toned <= knee
        ? toned
        : knee + (1.0 - knee) * (1.0 - exp(-(toned - knee) / max(1.0 - knee, 1e-9)));
    vec3 compositeLinear = (scene / norm) * min(toned, 1.0);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

export const HDR_BLOOM_STRATEGIES: Record<HdrBloomStrategyName, HdrBloomStrategy> = {
    'chroma-shoulder': {
        name: 'chroma-shoulder',
        label: 'chroma-shoulder (current)',
        description:
            'Shipped default. Bracket selection by white-merge risk, neutral/chroma '
            + 'split, exponential chroma shoulder from the high bracket.',
        brackets: STANDARD_BRACKETS,
        fragmentShader: CHROMA_SHOULDER_SHADER,
        supportsCpuOracle: true,
    },
    'linear-hdr': {
        name: 'linear-hdr',
        label: 'linear-hdr (2c51e78)',
        description:
            'First fully-linear composite. Pure bracket selection, bloom replaces the '
            + 'base, global 0.30 strength scale, no high-bracket threshold ramp.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 0.30,
            radiusScales: [1, 1, 1],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: LINEAR_HDR_SHADER,
        supportsCpuOracle: false,
    },
    'chroma-capped': {
        name: 'chroma-capped',
        label: 'chroma-capped (68d2550)',
        description:
            'Chroma from the mid bracket; neutral and chromatic energy capped together '
            + 'against one perceptual ceiling. Holds black well.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            radiusScales: [1, 1, 1],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: CHROMA_CAPPED_SHADER,
        supportsCpuOracle: false,
    },
    'white-core-chroma': {
        name: 'white-core-chroma',
        label: 'white-core-chroma (new)',
        description:
            'Fixes the degenerate white highlight: suppression is gated by raw '
            + 'saturation, and hue direction is taken from the most chromatic bracket '
            + 'while energy follows the selected one.',
        brackets: STANDARD_BRACKETS,
        fragmentShader: WHITE_CORE_CHROMA_SHADER,
        supportsCpuOracle: false,
    },
    'sliding-window': {
        name: 'sliding-window',
        label: 'sliding-window (new)',
        description:
            'Continuous exposure window between the low and high brackets positioned by '
            + 'per-pixel headroom. One interpolation, one shoulder, no discrete '
            + 'selection and no neutral/chroma split.',
        brackets: STANDARD_BRACKETS,
        fragmentShader: SLIDING_WINDOW_SHADER,
        supportsCpuOracle: false,
    },
    'wide-surround-chroma': {
        name: 'wide-surround-chroma',
        label: 'wide-surround-chroma (new)',
        description:
            'Gives the brackets real spatial separation and takes hue for blown '
            + 'highlights from the annulus around them, so a white core blooms in the '
            + 'colour of its surroundings instead of blooming white.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            // The wide bracket is the hue reference, not an intensity step.
            radiusScales: [1, 1, 3.2],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: WIDE_SURROUND_CHROMA_SHADER,
        supportsCpuOracle: false,
    },
    'surround-white-safe': {
        name: 'surround-white-safe',
        label: 'surround-white-safe (r2)',
        description:
            'wide-surround-chroma with the blown-core neutral penalty gated on '
            + 'surround purity, so a genuinely white LED keeps its white halo.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            radiusScales: [1, 1, 3.2],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: SURROUND_WHITE_SAFE_SHADER,
        supportsCpuOracle: false,
    },
    'norm-tonescale': {
        name: 'norm-tonescale',
        label: 'norm-tonescale (r2)',
        description:
            'Max-RGB-norm tonescale with hue-preserving ratio reconstruction and a '
            + 'bounded path-to-white. No white-merge heuristic exists to misfire.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            radiusScales: [1, 1, 2.2],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: NORM_TONESCALE_SHADER,
        supportsCpuOracle: false,
    },
    'surround-white-glow': {
        name: 'surround-white-glow',
        label: 'surround-white-glow (r3)',
        description:
            'surround-white-safe plus an asymmetric global-exposure relaxation and '
            + 'neutral ceiling for bright neutral sources, so white LEDs glow fully.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            radiusScales: [1, 1, 3.2],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: SURROUND_WHITE_GLOW_SHADER,
        supportsCpuOracle: false,
    },
    'norm-tonescale-guarded': {
        name: 'norm-tonescale-guarded',
        label: 'norm-tonescale-guarded (r3)',
        description:
            'norm-tonescale with the neutral component of added light gated by local '
            + 'sharp energy, closing the shadow veil that sank the unguarded version.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            radiusScales: [1, 1, 2.2],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: NORM_TONESCALE_GUARDED_SHADER,
        supportsCpuOracle: false,
    },
    'norm-tonescale-sharp': {
        name: 'norm-tonescale-sharp',
        label: 'norm-tonescale-sharp (r4)',
        description:
            'norm-tonescale-guarded weighted toward the tight bracket with a higher '
            + 'tonescale knee, trading halo width for LED-core contrast.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            radiusScales: [1, 1, 2.2],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: NORM_TONESCALE_SHARP_SHADER,
        supportsCpuOracle: false,
    },
    'norm-surround-hue': {
        name: 'norm-surround-hue',
        label: 'norm-surround-hue (r4)',
        description:
            'norm-tonescale-guarded plus the annulus hue reference: brightness from '
            + 'the tone-compressed norm, hue borrowed from the surround on blown cores.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            radiusScales: [1, 1, 3.2],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: NORM_SURROUND_HUE_SHADER,
        supportsCpuOracle: false,
    },
    'legacy-additive': {
        name: 'legacy-additive',
        label: 'legacy-additive (acrylic ref)',
        description:
            'Reconstruction of the pre-HDR additive bloom, per-channel clamp and '
            + 'all. The acrylic directive\'s reference for diffusion response.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            radiusScales: [1, 1.6, 3.2],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: LEGACY_ADDITIVE_SHADER,
        supportsCpuOracle: false,
    },
    'acrylic-overflow': {
        name: 'acrylic-overflow',
        label: 'acrylic-overflow (r5)',
        description:
            'Legacy bloom energy with hue-locked overflow: past threshold, excess '
            + 'light goes outward into the wide lobe instead of clipping to white.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            radiusScales: [1, 1.6, 3.2],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: ACRYLIC_OVERFLOW_SHADER,
        supportsCpuOracle: false,
    },
    'acrylic-pane-wide': {
        name: 'acrylic-pane-wide',
        label: 'acrylic-pane-wide (r6 historical)',
        description:
            'Historical acrylic-pane response with all five UnrealBloom mips. '
            + 'Retained as the reproducible baseline for low-frequency color-wash tests.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            radiusScales: [1, 1.6, 3.2],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: ACRYLIC_PANE_SHADER,
        supportsCpuOracle: false,
    },
    'acrylic-pane': {
        name: 'acrylic-pane',
        label: 'acrylic-pane (local bloom)',
        description:
            'acrylic-overflow plus drive-dependent core softening: inside hot '
            + 'regions the base blends toward the diffused field, so fully driven '
            + 'dots merge into one pane instead of staying sharp over a glow. '
            + 'UnrealBloom mips 1-2 plus a restrained mip 3 contribute, restoring '
            + 'midtone surface fill while mips 4-5 remain disabled to prevent '
            + 'coarse scene-wide color wash.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            // Splat look: tight lobe carries the visible Gaussian falloff;
            // the wide lobe (kept at 3.2 for flare reach) is a faint tail.
            radiusScales: [1, 1.6, 3.2],
            highThresholdDark: 0,
            highThresholdBright: 0,
            // Removing the two coarsest bands discards the scene-scale field.
            // Most energy stays concentrated in the two local bands:
            // level 1 covers each LED body/immediate skirt; level 2 reaches
            // the nearest axial and diagonal neighbours. A restrained level 3
            // restores the lower-quartile gap fill needed by complex faces,
            // while the spatial chroma-leak gate keeps its far-field pull below
            // the red-petal/blue-neighbour ceiling.
            unrealMipWeights: [2.85, 1.5, 0.25, 0, 0],
        },
        fragmentShader: ACRYLIC_PANE_SHADER,
        supportsCpuOracle: false,
    },
    'acrylic-psf': {
        name: 'acrylic-psf',
        label: 'acrylic-psf (r7)',
        description:
            'Fixed intensity-independent three-lobe PSF, pure linear superposition, '
            + 'hue-locked clip at display: the white-out and glow growth emerge from '
            + 'the physics instead of drive-dependent gates.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            radiusScales: [1, 1.6, 3.2],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: ACRYLIC_PSF_SHADER,
        supportsCpuOracle: false,
    },
    'acrylic-native': {
        name: 'acrylic-native',
        label: 'acrylic-native (r9 owned pipeline)',
        description:
            'Owned PSF pipeline: coverage-normalized emission fields replace '
            + 'UnrealBloom, so halos carry undiluted local hue and rims cannot '
            + 'ring; energy admission keeps the visibility-threshold physics.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            radiusScales: [1, 1.6, 4.4],
            highThresholdDark: 0,
            highThresholdBright: 0,
            customPsf: true,
        },
        fragmentShader: ACRYLIC_NATIVE_SHADER,
        supportsCpuOracle: false,
    },
    'hdr-reference': {
        name: 'hdr-reference',
        label: 'hdr-reference (#496 P2)',
        description:
            'Reference composite on the owned pipeline: additive HDR splats, '
            + 'coverage-admitted glow (drive-independent veil control), one '
            + 'hue-locked norm tone map.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            radiusScales: [1, 1.6, 3.2],
            highThresholdDark: 0,
            highThresholdBright: 0,
            customPsf: true,
        },
        fragmentShader: HDR_REFERENCE_SHADER,
        supportsCpuOracle: false,
    },
};

export function isHdrBloomStrategyName(value: string): value is HdrBloomStrategyName {
    return (HDR_BLOOM_STRATEGY_NAMES as readonly string[]).includes(value);
}

/**
 * Names reaching this from a URL are validated by the production contract's
 * `strictEnum`, so the record lookup is total.
 */
export function resolveHdrBloomStrategy(name: HdrBloomStrategyName): HdrBloomStrategy {
    return HDR_BLOOM_STRATEGIES[name];
}
