/**
 * HDR bloom composite strategies.
 *
 * Each strategy is one complete answer to "how should the sharp scene and the
 * three bloom brackets become one image". Strategies are kept side by side
 * rather than replaced so visual experiments stay reproducible: a render from
 * six months ago can be regenerated by name instead of by git archaeology.
 *
 * A strategy owns both halves of the algorithm:
 *   - `brackets`, consumed by the bracket-capture loop in `preview.ts`, and
 *   - `fragmentShader`, the composite itself.
 *
 * These co-evolved historically (the linear-hdr strategy scales bloom strength
 * globally; only chroma-shoulder ramps the high bracket's threshold), so a
 * shader alone does not reproduce a past render.
 */

/** Bracket-capture parameters. Index order is always [low, mid, high]. */
export interface HdrBloomBracketConfig {
    /** Per-bracket multipliers applied to the configured bloom strength. */
    factors: readonly [number, number, number];
    /** Global multiplier applied to bloom strength before the factors. */
    strengthScale: number;
    /**
     * Per-bracket multipliers on the bloom blur radius.
     *
     * All-1 (the historical setup) makes the three brackets differ only in
     * intensity: they are near-scalar multiples of one another, so no amount of
     * bracket selection can recover information one of them lacks. Giving a
     * bracket a wider radius makes it a genuinely different spatial scale,
     * which is what lets a blown-out highlight pick up the hue of the region
     * around it instead of its own white core.
     */
    radiusScales: readonly [number, number, number];
    /** High-bracket bloom threshold at globalBloomBias 0. */
    highThresholdDark: number;
    /** High-bracket bloom threshold at globalBloomBias 1. */
    highThresholdBright: number;
}

export interface HdrBloomStrategy {
    name: HdrBloomStrategyName;
    /** Short label burned into comparison grids. */
    label: string;
    description: string;
    brackets: HdrBloomBracketConfig;
    fragmentShader: string;
    /**
     * Whether `bloom-utils.compositeHdrBloomRgba` mirrors this shader. Only the
     * default strategy has a CPU oracle; verifying any other against it would
     * compare two different algorithms.
     */
    supportsCpuOracle: boolean;
}

export const HDR_BLOOM_STRATEGY_NAMES = [
    'chroma-shoulder',
    'linear-hdr',
    'chroma-capped',
    'white-core-chroma',
    'sliding-window',
    'wide-surround-chroma',
] as const;

export type HdrBloomStrategyName = (typeof HDR_BLOOM_STRATEGY_NAMES)[number];

export const DEFAULT_HDR_BLOOM_STRATEGY: HdrBloomStrategyName = 'chroma-shoulder';

/** Bracket setup used by every strategy that did not customize it. */
const STANDARD_BRACKETS: HdrBloomBracketConfig = {
    factors: [0.20, 0.55, 1],
    strengthScale: 1,
    radiusScales: [1, 1, 1],
    highThresholdDark: 0.08,
    highThresholdBright: 0.16,
};

/** Shared GLSL: transfer functions and the v1-compatible smoothstep. */
const PRELUDE = /* glsl */`
precision highp float;

uniform sampler2D rawFrame;
uniform sampler2D lowFrame;
uniform sampler2D midFrame;
uniform sampler2D highFrame;
uniform float globalBloomBias;
varying vec2 vUv;

float v1Smoothstep(float edge0, float edge1, float value) {
    float t = clamp((value - edge0) / max(edge1 - edge0, 1e-9), 0.0, 1.0);
    return t * t * (3.0 - 2.0 * t);
}

vec3 linearToSrgb(vec3 value) {
    value = max(value, vec3(0.0));
    bvec3 cutoff = lessThanEqual(value, vec3(0.0031308));
    vec3 lower = value * 12.92;
    vec3 higher = 1.055 * pow(value, vec3(1.0 / 2.4)) - 0.055;
    return mix(higher, lower, cutoff);
}

float srgbToLinear(float value) {
    return value <= 0.04045
        ? value / 12.92
        : pow((value + 0.055) / 1.055, 2.4);
}

float maxChannel(vec3 value) { return max(max(value.r, value.g), value.b); }
float minChannel(vec3 value) { return min(min(value.r, value.g), value.b); }
`;

/** The white-merge detector shared by the three historical strategies. */
const V1_RISK_FUNCTIONS = /* glsl */`
float pixelWhiteMergeRisk(vec3 raw, vec3 bloomed) {
    float rawMax = maxChannel(raw);
    if (rawMax < 0.04) return 0.0;
    float rawMin = minChannel(raw);
    float bloomMax = maxChannel(bloomed);
    float bloomMin = minChannel(bloomed);
    float rawSaturation = (rawMax - rawMin) / max(rawMax, 1e-9);
    float bloomSaturation = (bloomMax - bloomMin) / max(bloomMax, 1e-9);
    float colorWash = v1Smoothstep(0.72, 0.98, bloomMin)
        * max(rawSaturation - bloomSaturation, 0.0);
    float clippedDetail = v1Smoothstep(0.82, 0.995, bloomMax)
        * v1Smoothstep(0.03, 0.22, bloomMax - rawMax)
        * v1Smoothstep(0.30, 0.85, rawMax);
    return max(colorWash, clippedDetail * 0.65);
}

float shadowBloomWeight(vec3 raw, vec3 bloomed) {
    float rawMax = maxChannel(raw);
    if (rawMax >= 0.04) return 1.0;
    float bloomMax = maxChannel(bloomed);
    return v1Smoothstep(0.025, 0.14, bloomMax);
}
`;

/**
 * Current production shader (commit 584baa8), preserved verbatim so the default
 * strategy stays byte-identical to renders made before the registry existed.
 */
const CHROMA_SHOULDER_SHADER = PRELUDE + V1_RISK_FUNCTIONS + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    vec3 raw = linearToSrgb(rawLinear);
    vec3 mid = linearToSrgb(midLinear);
    vec3 high = linearToSrgb(highLinear);
    float highRisk = pixelWhiteMergeRisk(raw, high);
    float midRisk = pixelWhiteMergeRisk(raw, mid);
    float highWeight = (1.0 - v1Smoothstep(0.035, 0.20, highRisk))
        * mix(1.0, 0.15, globalBloomBias);
    float midWeight = (1.0 - v1Smoothstep(0.05, 0.24, midRisk))
        * mix(1.0, 0.35, globalBloomBias);
    vec3 upperLinear = mix(midLinear, highLinear, highWeight);
    vec3 selectedLinear = mix(lowLinear, upperLinear, midWeight);

    vec3 selectedAdded = max(selectedLinear - rawLinear, vec3(0.0));
    float neutralBloom = minChannel(selectedAdded);
    float protectedNeutral = neutralBloom * shadowBloomWeight(raw, high);

    vec3 highAdded = max(highLinear - rawLinear, vec3(0.0));
    float highNeutral = minChannel(highAdded);
    vec3 highChroma = max(highAdded - vec3(highNeutral), vec3(0.0));
    float highAddedEnergy = maxChannel(highAdded);
    float chromaEnergy = maxChannel(highChroma);
    float chromaPurity = chromaEnergy / max(highAddedEnergy, 1e-9);
    float sceneChromaScale = mix(1.0, 0.65, globalBloomBias);
    float chromaGate = v1Smoothstep(srgbToLinear(0.015), srgbToLinear(0.07), chromaEnergy)
        * v1Smoothstep(0.08, 0.40, chromaPurity)
        * sceneChromaScale;

    float chromaShoulder = srgbToLinear(0.40);
    float mappedChromaEnergy = chromaShoulder
        * (1.0 - exp(-chromaEnergy / max(chromaShoulder, 1e-9)));
    float chromaScale = chromaEnergy > 1e-9
        ? mappedChromaEnergy / chromaEnergy
        : 0.0;
    vec3 chromaticBloom = highChroma * chromaScale * chromaGate;

    float saturationProtection = v1Smoothstep(0.15, 0.65, chromaPurity);
    protectedNeutral *= mix(1.0, 0.30, saturationProtection);

    float rawMax = maxChannel(raw);
    float darkMask = 1.0 - v1Smoothstep(0.02, 0.12, rawMax);
    float baseLimitSrgb = mix(0.18, 0.11, globalBloomBias);
    float neutralLimit = mix(1.0, srgbToLinear(baseLimitSrgb), darkMask);
    float neutralHeadroom = max(minChannel(vec3(1.0) - rawLinear), 0.0);
    float neutralAdded = min(min(protectedNeutral, neutralLimit), neutralHeadroom);

    vec3 baseWithNeutral = rawLinear + vec3(neutralAdded);
    vec3 available = max(vec3(1.0) - baseWithNeutral, vec3(0.0));
    float hueSafeScale = 1.0;
    if (chromaticBloom.r > 1e-9) hueSafeScale = min(hueSafeScale, available.r / chromaticBloom.r);
    if (chromaticBloom.g > 1e-9) hueSafeScale = min(hueSafeScale, available.g / chromaticBloom.g);
    if (chromaticBloom.b > 1e-9) hueSafeScale = min(hueSafeScale, available.b / chromaticBloom.b);
    vec3 compositeLinear = baseWithNeutral + chromaticBloom * clamp(hueSafeScale, 0.0, 1.0);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * Resurrected from commit 2c51e78 "Preserve color through linear HDR bloom".
 * The first fully-linear composite: pure bracket selection, no neutral/chroma
 * split. Bloom replaces the base rather than adding to it, which is why it
 * needed the 0.30 global strength scale to stay controlled.
 */
const LINEAR_HDR_SHADER = PRELUDE + V1_RISK_FUNCTIONS + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    vec3 raw = linearToSrgb(rawLinear);
    vec3 mid = linearToSrgb(midLinear);
    vec3 high = linearToSrgb(highLinear);
    float highRisk = pixelWhiteMergeRisk(raw, high);
    float midRisk = pixelWhiteMergeRisk(raw, mid);
    float highWeight = 1.0 - v1Smoothstep(0.035, 0.20, highRisk);
    float midWeight = 1.0 - v1Smoothstep(0.05, 0.24, midRisk);
    vec3 upperLinear = mix(midLinear, highLinear, highWeight);
    vec3 bloomCompositeLinear = mix(lowLinear, upperLinear, midWeight);
    vec3 compositeLinear = mix(
        rawLinear,
        bloomCompositeLinear,
        shadowBloomWeight(raw, high)
    );

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * Resurrected from commit 68d2550 "Preserve chromatic bloom without lifting
 * shadows". Takes chroma from the mid bracket and caps neutral + chromatic
 * energy together against one perceptual ceiling, which is the reason it holds
 * black better than linear-hdr.
 */
const CHROMA_CAPPED_SHADER = PRELUDE + V1_RISK_FUNCTIONS + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    vec3 raw = linearToSrgb(rawLinear);
    vec3 mid = linearToSrgb(midLinear);
    vec3 high = linearToSrgb(highLinear);
    float highRisk = pixelWhiteMergeRisk(raw, high);
    float midRisk = pixelWhiteMergeRisk(raw, mid);
    float highWeight = 1.0 - v1Smoothstep(0.035, 0.20, highRisk);
    float midWeight = 1.0 - v1Smoothstep(0.05, 0.24, midRisk);
    vec3 upperLinear = mix(midLinear, highLinear, highWeight);
    vec3 selectedLinear = mix(lowLinear, upperLinear, midWeight);

    vec3 selectedAdded = max(selectedLinear - rawLinear, vec3(0.0));
    float neutralBloom = minChannel(selectedAdded);
    float protectedNeutral = neutralBloom * shadowBloomWeight(raw, high);

    vec3 midAdded = max(midLinear - rawLinear, vec3(0.0));
    float midAddedNeutral = minChannel(midAdded);
    vec3 chromaticBloom = max(midAdded - vec3(midAddedNeutral), vec3(0.0));
    float chromaEnergy = maxChannel(chromaticBloom);

    float chromaGate = v1Smoothstep(
        srgbToLinear(0.02),
        srgbToLinear(0.08),
        chromaEnergy
    );
    float darkMask = 1.0 - v1Smoothstep(0.02, 0.12, maxChannel(raw));
    vec3 addedBloom = vec3(protectedNeutral) + chromaticBloom * chromaGate;
    float addedEnergy = maxChannel(addedBloom);
    float addedLimit = mix(1.0, srgbToLinear(0.18), darkMask);
    float addedScale = addedEnergy > 1e-9
        ? min(1.0, addedLimit / addedEnergy)
        : 0.0;

    vec3 bloomHeadroom = max(vec3(1.0) - rawLinear, vec3(0.0));
    vec3 compositeLinear = rawLinear
        + min(addedBloom * addedScale, bloomHeadroom);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * Targets the degenerate white-highlight condition.
 *
 * Two failures compound on a blown white core in the shipped strategy:
 *
 *  1. `clippedDetail` fires all three of its smoothsteps on a bright achromatic
 *     pixel, so risk saturates and the high bracket is weighted to ~0. Bloom
 *     switches off exactly where it matters most. But the detector exists to
 *     stop bloom from washing *color* out â€” on a pixel whose raw value is
 *     already achromatic there is no hue to protect, so the suppression buys
 *     nothing and costs the halo. Here the clipped-detail term is gated by raw
 *     saturation.
 *  2. Chroma is sourced from `high - raw`. A blown core's high bracket is white
 *     too, so the chroma vector collapses to zero and the halo has no color
 *     left to carry. Here the hue *direction* comes from whichever bracket has
 *     the most chromatic purity (the wider, dimmer brackets still see the
 *     colored surround), while the *energy* still comes from the selected
 *     bracket. Direction and intensity are decoupled.
 */
const WHITE_CORE_CHROMA_SHADER = PRELUDE + /* glsl */`
float chromaPurityOf(vec3 added) {
    float energy = maxChannel(added);
    if (energy < 1e-9) return 0.0;
    return (energy - minChannel(added)) / energy;
}

/** Unit-ish chroma direction: the added colour with its neutral part removed. */
vec3 chromaVector(vec3 added) {
    return max(added - vec3(minChannel(added)), vec3(0.0));
}

float saturationOf(vec3 value) {
    float m = maxChannel(value);
    if (m < 1e-9) return 0.0;
    return (m - minChannel(value)) / m;
}

/**
 * White-merge risk that only fires when there is chroma at stake. The colorWash
 * term already self-cancels on achromatic input; the clippedDetail term does
 * not, so it is scaled by how much saturation the raw pixel actually has.
 */
float chromaAwareRisk(vec3 raw, vec3 bloomed) {
    float rawMax = maxChannel(raw);
    if (rawMax < 0.04) return 0.0;
    float bloomMax = maxChannel(bloomed);
    float bloomMin = minChannel(bloomed);
    float rawSaturation = saturationOf(raw);
    float bloomSaturation = (bloomMax - bloomMin) / max(bloomMax, 1e-9);
    float colorWash = v1Smoothstep(0.72, 0.98, bloomMin)
        * max(rawSaturation - bloomSaturation, 0.0);
    float clippedDetail = v1Smoothstep(0.82, 0.995, bloomMax)
        * v1Smoothstep(0.03, 0.22, bloomMax - rawMax)
        * v1Smoothstep(0.30, 0.85, rawMax)
        * v1Smoothstep(0.04, 0.18, rawSaturation);
    return max(colorWash, clippedDetail * 0.65);
}

float shadowBloomWeight(vec3 raw, vec3 bloomed) {
    float rawMax = maxChannel(raw);
    if (rawMax >= 0.04) return 1.0;
    return v1Smoothstep(0.025, 0.14, maxChannel(bloomed));
}

void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    vec3 raw = linearToSrgb(rawLinear);
    vec3 mid = linearToSrgb(midLinear);
    vec3 high = linearToSrgb(highLinear);
    float highRisk = chromaAwareRisk(raw, high);
    float midRisk = chromaAwareRisk(raw, mid);
    float highWeight = (1.0 - v1Smoothstep(0.035, 0.20, highRisk))
        * mix(1.0, 0.15, globalBloomBias);
    float midWeight = (1.0 - v1Smoothstep(0.05, 0.24, midRisk))
        * mix(1.0, 0.35, globalBloomBias);
    vec3 upperLinear = mix(midLinear, highLinear, highWeight);
    vec3 selectedLinear = mix(lowLinear, upperLinear, midWeight);

    vec3 lowAdded = max(lowLinear - rawLinear, vec3(0.0));
    vec3 midAdded = max(midLinear - rawLinear, vec3(0.0));
    vec3 highAdded = max(highLinear - rawLinear, vec3(0.0));
    vec3 selectedAdded = max(selectedLinear - rawLinear, vec3(0.0));

    float neutralBloom = minChannel(selectedAdded);
    float protectedNeutral = neutralBloom * shadowBloomWeight(raw, high);

    // Hue reference: the bracket that still carries colour. A blown highlight
    // whites out the high bracket first and the low bracket last, so this
    // walks down the stack instead of giving up.
    float highPurity = chromaPurityOf(highAdded);
    float midPurity = chromaPurityOf(midAdded);
    float lowPurity = chromaPurityOf(lowAdded);
    vec3 referenceChroma = chromaVector(highAdded);
    float referencePurity = highPurity;
    if (midPurity > referencePurity) {
        referenceChroma = chromaVector(midAdded);
        referencePurity = midPurity;
    }
    if (lowPurity > referencePurity) {
        referenceChroma = chromaVector(lowAdded);
        referencePurity = lowPurity;
    }
    float referenceEnergy = maxChannel(referenceChroma);
    vec3 chromaDirection = referenceEnergy > 1e-9
        ? referenceChroma / referenceEnergy
        : vec3(0.0);

    // Energy comes from the selected bracket, so intensity still tracks the
    // exposure decision even when the hue came from a dimmer bracket.
    float selectedEnergy = maxChannel(selectedAdded);
    float chromaEnergy = selectedEnergy * referencePurity;
    float sceneChromaScale = mix(1.0, 0.65, globalBloomBias);
    float chromaGate = v1Smoothstep(srgbToLinear(0.015), srgbToLinear(0.07), chromaEnergy)
        * v1Smoothstep(0.05, 0.30, referencePurity)
        * sceneChromaScale;

    float chromaShoulder = srgbToLinear(0.40);
    float mappedChromaEnergy = chromaShoulder
        * (1.0 - exp(-chromaEnergy / max(chromaShoulder, 1e-9)));
    vec3 chromaticBloom = chromaDirection * mappedChromaEnergy * chromaGate;

    float saturationProtection = v1Smoothstep(0.15, 0.65, referencePurity);
    protectedNeutral *= mix(1.0, 0.30, saturationProtection);

    float rawMax = maxChannel(raw);
    float darkMask = 1.0 - v1Smoothstep(0.02, 0.12, rawMax);
    float baseLimitSrgb = mix(0.18, 0.11, globalBloomBias);
    float neutralLimit = mix(1.0, srgbToLinear(baseLimitSrgb), darkMask);
    float neutralHeadroom = max(minChannel(vec3(1.0) - rawLinear), 0.0);
    float neutralAdded = min(min(protectedNeutral, neutralLimit), neutralHeadroom);

    vec3 baseWithNeutral = rawLinear + vec3(neutralAdded);
    vec3 available = max(vec3(1.0) - baseWithNeutral, vec3(0.0));
    float hueSafeScale = 1.0;
    if (chromaticBloom.r > 1e-9) hueSafeScale = min(hueSafeScale, available.r / chromaticBloom.r);
    if (chromaticBloom.g > 1e-9) hueSafeScale = min(hueSafeScale, available.g / chromaticBloom.g);
    if (chromaticBloom.b > 1e-9) hueSafeScale = min(hueSafeScale, available.b / chromaticBloom.b);
    vec3 compositeLinear = baseWithNeutral + chromaticBloom * clamp(hueSafeScale, 0.0, 1.0);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * Sliding-window reactive bloom: no discrete bracket selection and no
 * neutral/chroma split.
 *
 * The three brackets are treated as samples of one continuous exposure curve
 * between a minimum (low) and maximum (high) bloom. A single per-pixel position
 * along that window is chosen from how much headroom the raw pixel has left,
 * and the composite is one interpolation at that point. Where the base is
 * already near clipping the window slides toward the low end, so a blown
 * highlight gets a narrow tight halo instead of the bloom being switched off
 * entirely â€” the failure the discrete selector has on white cores.
 */
const SLIDING_WINDOW_SHADER = PRELUDE + /* glsl */`
void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 lowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 highLinear = texture2D(highFrame, vUv).rgb;

    vec3 raw = linearToSrgb(rawLinear);
    float rawMax = maxChannel(raw);

    // Window position: 1 = full high bracket, 0 = low bracket only. Headroom
    // drives it, so bright pixels slide down the window continuously rather
    // than falling off a threshold.
    float headroom = 1.0 - v1Smoothstep(0.45, 0.97, rawMax);
    float window = headroom * mix(1.0, 0.45, globalBloomBias);

    // One interpolation across the whole stack: low -> mid over the first half
    // of the window, mid -> high over the second.
    float lowerBlend = clamp(window * 2.0, 0.0, 1.0);
    float upperBlend = clamp(window * 2.0 - 1.0, 0.0, 1.0);
    vec3 windowed = mix(mix(lowLinear, midLinear, lowerBlend), highLinear, upperBlend);

    // Bloom is added light, never a replacement for the sharp base.
    vec3 added = max(windowed - rawLinear, vec3(0.0));

    // Fade added light out in true black so inter-LED gaps keep their contrast.
    float shadowGate = rawMax >= 0.04
        ? 1.0
        : v1Smoothstep(0.025, 0.14, maxChannel(linearToSrgb(windowed)));

    // One uniform-vector shoulder on the whole added colour. Scaling the vector
    // rather than clipping channels is what keeps a saturated halo saturated as
    // it brightens.
    float addedEnergy = maxChannel(added);
    float shoulder = srgbToLinear(mix(0.42, 0.26, globalBloomBias));
    float mappedEnergy = shoulder * (1.0 - exp(-addedEnergy / max(shoulder, 1e-9)));
    float energyScale = addedEnergy > 1e-9 ? mappedEnergy / addedEnergy : 0.0;
    vec3 shaped = added * energyScale * shadowGate;

    // Single hue-safe gamut scale; never clip channels independently.
    vec3 available = max(vec3(1.0) - rawLinear, vec3(0.0));
    float hueSafeScale = 1.0;
    if (shaped.r > 1e-9) hueSafeScale = min(hueSafeScale, available.r / shaped.r);
    if (shaped.g > 1e-9) hueSafeScale = min(hueSafeScale, available.g / shaped.g);
    if (shaped.b > 1e-9) hueSafeScale = min(hueSafeScale, available.b / shaped.b);
    vec3 compositeLinear = rawLinear + shaped * clamp(hueSafeScale, 0.0, 1.0);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

/**
 * Recovers hue for a blown-out highlight from the region around it.
 *
 * Measurement of `white-core-chroma` showed why gating the white detector was
 * not enough: with all-1 radius scales the three brackets are the same blur at
 * three intensities, so they are near-scalar multiples and every one of them is
 * white at a white core. No selection among them can produce colour that none
 * of them has.
 *
 * This strategy pairs its shader with genuinely different spatial scales
 * (`radiusScales`), which makes the high bracket a wide blur whose value at the
 * core is dominated by the *surrounding* pixels. The annulus estimate
 * `wide - narrow` then isolates that surround: it is the light arriving from
 * around the highlight rather than from the highlight itself, and it still
 * carries the scene's hue when the core has none. Bloom energy stays tied to
 * the narrow brackets so halo size does not balloon.
 */
const WIDE_SURROUND_CHROMA_SHADER = PRELUDE + /* glsl */`
float saturationOf(vec3 value) {
    float m = maxChannel(value);
    if (m < 1e-9) return 0.0;
    return (m - minChannel(value)) / m;
}

void main() {
    vec3 rawLinear = texture2D(rawFrame, vUv).rgb;
    vec3 narrowLinear = texture2D(lowFrame, vUv).rgb;
    vec3 midLinear = texture2D(midFrame, vUv).rgb;
    vec3 wideLinear = texture2D(highFrame, vUv).rgb;

    vec3 raw = linearToSrgb(rawLinear);
    float rawMax = maxChannel(raw);
    float rawSaturation = saturationOf(raw);

    vec3 narrowAdded = max(narrowLinear - rawLinear, vec3(0.0));
    vec3 midAdded = max(midLinear - rawLinear, vec3(0.0));
    vec3 wideAdded = max(wideLinear - rawLinear, vec3(0.0));

    // Annulus: light from around this pixel rather than from it. The wide
    // bracket minus the narrow one removes the core's own contribution, which
    // is exactly the part that has gone achromatic on a blown highlight.
    vec3 surround = max(wideAdded - midAdded, vec3(0.0));
    float surroundEnergy = maxChannel(surround);
    vec3 surroundChroma = max(surround - vec3(minChannel(surround)), vec3(0.0));
    float surroundChromaEnergy = maxChannel(surroundChroma);
    float surroundPurity = surroundChromaEnergy / max(surroundEnergy, 1e-9);
    vec3 surroundDirection = surroundChromaEnergy > 1e-9
        ? surroundChroma / surroundChromaEnergy
        : vec3(0.0);

    // Local chroma, used wherever the pixel still has colour of its own.
    vec3 localChroma = max(midAdded - vec3(minChannel(midAdded)), vec3(0.0));
    float localChromaEnergy = maxChannel(localChroma);
    vec3 localDirection = localChromaEnergy > 1e-9
        ? localChroma / localChromaEnergy
        : vec3(0.0);

    // Blend toward the surround exactly where the local signal has lost its
    // hue: bright and desaturated. Elsewhere this is a no-op, so ordinary
    // coloured highlights behave as before.
    float blownOut = v1Smoothstep(0.55, 0.92, rawMax)
        * (1.0 - v1Smoothstep(0.05, 0.22, rawSaturation));
    vec3 chromaDirection = normalize(mix(localDirection, surroundDirection, blownOut)
        + vec3(1e-6));
    float directionPurity = mix(
        localChromaEnergy / max(maxChannel(midAdded), 1e-9),
        surroundPurity,
        blownOut
    );

    // Energy from the narrow brackets so a wide hue reference cannot inflate
    // the halo. Neutral energy is the only part that can drive toward white,
    // so it stays under the global exposure bias.
    float neutralBloom = minChannel(midAdded);
    float sceneScale = mix(1.0, 0.35, globalBloomBias);
    float protectedNeutral = neutralBloom * sceneScale;
    if (rawMax < 0.04) {
        protectedNeutral *= v1Smoothstep(0.025, 0.14, maxChannel(linearToSrgb(midLinear)));
    }

    float chromaEnergy = maxChannel(midAdded) * directionPurity
        * mix(1.0, 0.65, globalBloomBias);
    float chromaShoulder = srgbToLinear(0.40);
    float mappedChromaEnergy = chromaShoulder
        * (1.0 - exp(-chromaEnergy / max(chromaShoulder, 1e-9)));
    float chromaGate = v1Smoothstep(srgbToLinear(0.010), srgbToLinear(0.055), chromaEnergy);
    vec3 chromaticBloom = chromaDirection * mappedChromaEnergy * chromaGate;

    // Saturated results need less neutral lift; blown cores need less still,
    // because neutral energy there is what produced the white in the first
    // place.
    protectedNeutral *= mix(1.0, 0.30, v1Smoothstep(0.15, 0.65, directionPurity));
    protectedNeutral *= mix(1.0, 0.45, blownOut);

    float darkMask = 1.0 - v1Smoothstep(0.02, 0.12, rawMax);
    float baseLimitSrgb = mix(0.18, 0.11, globalBloomBias);
    float neutralLimit = mix(1.0, srgbToLinear(baseLimitSrgb), darkMask);
    float neutralHeadroom = max(minChannel(vec3(1.0) - rawLinear), 0.0);
    float neutralAdded = min(min(protectedNeutral, neutralLimit), neutralHeadroom);

    vec3 baseWithNeutral = rawLinear + vec3(neutralAdded);
    vec3 available = max(vec3(1.0) - baseWithNeutral, vec3(0.0));
    float hueSafeScale = 1.0;
    if (chromaticBloom.r > 1e-9) hueSafeScale = min(hueSafeScale, available.r / chromaticBloom.r);
    if (chromaticBloom.g > 1e-9) hueSafeScale = min(hueSafeScale, available.g / chromaticBloom.g);
    if (chromaticBloom.b > 1e-9) hueSafeScale = min(hueSafeScale, available.b / chromaticBloom.b);
    vec3 compositeLinear = baseWithNeutral + chromaticBloom * clamp(hueSafeScale, 0.0, 1.0);

    gl_FragColor = vec4(clamp(linearToSrgb(compositeLinear), 0.0, 1.0), 1.0);
}
`;

export const HDR_BLOOM_STRATEGIES: Record<HdrBloomStrategyName, HdrBloomStrategy> = {
    'chroma-shoulder': {
        name: 'chroma-shoulder',
        label: 'chroma-shoulder (current)',
        description:
            'Shipped default. Bracket selection by white-merge risk, neutral/chroma '
            + 'split, exponential chroma shoulder from the high bracket.',
        brackets: STANDARD_BRACKETS,
        fragmentShader: CHROMA_SHOULDER_SHADER,
        supportsCpuOracle: true,
    },
    'linear-hdr': {
        name: 'linear-hdr',
        label: 'linear-hdr (2c51e78)',
        description:
            'First fully-linear composite. Pure bracket selection, bloom replaces the '
            + 'base, global 0.30 strength scale, no high-bracket threshold ramp.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 0.30,
            radiusScales: [1, 1, 1],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: LINEAR_HDR_SHADER,
        supportsCpuOracle: false,
    },
    'chroma-capped': {
        name: 'chroma-capped',
        label: 'chroma-capped (68d2550)',
        description:
            'Chroma from the mid bracket; neutral and chromatic energy capped together '
            + 'against one perceptual ceiling. Holds black well.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            radiusScales: [1, 1, 1],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: CHROMA_CAPPED_SHADER,
        supportsCpuOracle: false,
    },
    'white-core-chroma': {
        name: 'white-core-chroma',
        label: 'white-core-chroma (new)',
        description:
            'Fixes the degenerate white highlight: suppression is gated by raw '
            + 'saturation, and hue direction is taken from the most chromatic bracket '
            + 'while energy follows the selected one.',
        brackets: STANDARD_BRACKETS,
        fragmentShader: WHITE_CORE_CHROMA_SHADER,
        supportsCpuOracle: false,
    },
    'sliding-window': {
        name: 'sliding-window',
        label: 'sliding-window (new)',
        description:
            'Continuous exposure window between the low and high brackets positioned by '
            + 'per-pixel headroom. One interpolation, one shoulder, no discrete '
            + 'selection and no neutral/chroma split.',
        brackets: STANDARD_BRACKETS,
        fragmentShader: SLIDING_WINDOW_SHADER,
        supportsCpuOracle: false,
    },
    'wide-surround-chroma': {
        name: 'wide-surround-chroma',
        label: 'wide-surround-chroma (new)',
        description:
            'Gives the brackets real spatial separation and takes hue for blown '
            + 'highlights from the annulus around them, so a white core blooms in the '
            + 'colour of its surroundings instead of blooming white.',
        brackets: {
            factors: [0.20, 0.55, 1],
            strengthScale: 1,
            // The wide bracket is the hue reference, not an intensity step.
            radiusScales: [1, 1, 3.2],
            highThresholdDark: 0,
            highThresholdBright: 0,
        },
        fragmentShader: WIDE_SURROUND_CHROMA_SHADER,
        supportsCpuOracle: false,
    },
};

export function isHdrBloomStrategyName(value: string): value is HdrBloomStrategyName {
    return (HDR_BLOOM_STRATEGY_NAMES as readonly string[]).includes(value);
}

/**
 * Names reaching this from a URL are validated by the production contract's
 * `strictEnum`, so the record lookup is total.
 */
export function resolveHdrBloomStrategy(name: HdrBloomStrategyName): HdrBloomStrategy {
    return HDR_BLOOM_STRATEGIES[name];
}

